/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

/**
 *
 * @author Sebastián
 */
public class Consultar_estado extends javax.swing.JFrame {


    public Consultar_estado() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.ver_estado.setLocationRelativeTo(null);
        this.Seguir_consultas.setLocationRelativeTo(null);
        this.ver_estado.setSize(390, 350);
        this.Seguir_consultas.setSize(450, 155);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ver_estado = new javax.swing.JFrame();
        jScrollPane2 = new javax.swing.JScrollPane();
        Comentarios_servicio = new javax.swing.JTextArea();
        jLabel14 = new javax.swing.JLabel();
        Continuar_estado = new javax.swing.JButton();
        Fecha_mod_servicio = new javax.swing.JTextField();
        Hora_mod_servicio = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        Esta_servicio = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        Seguir_consultas = new javax.swing.JDialog();
        jLabel15 = new javax.swing.JLabel();
        Si_seguir_consul = new javax.swing.JButton();
        No_seguir_consul = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        Consultar_estado = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        Num_servicio = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        Fecha_crea_servicio = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        Tipo_doc = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        Num_doc = new javax.swing.JTextField();
        Volver = new javax.swing.JButton();

        ver_estado.setTitle("En desarrollo");

        Comentarios_servicio.setColumns(20);
        Comentarios_servicio.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        Comentarios_servicio.setLineWrap(true);
        Comentarios_servicio.setWrapStyleWord(true);
        jScrollPane2.setViewportView(Comentarios_servicio);

        jLabel14.setText("Comentarios:");

        Continuar_estado.setText("Continuar");
        Continuar_estado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Continuar_estadoActionPerformed(evt);
            }
        });

        jLabel4.setText("El estado del servicio indicado, es el siguiente:");

        jLabel7.setText("Estado:");

        jLabel8.setText("<html>Hora de modificación:");

        jLabel9.setText("Fecha de modificación:");

        javax.swing.GroupLayout ver_estadoLayout = new javax.swing.GroupLayout(ver_estado.getContentPane());
        ver_estado.getContentPane().setLayout(ver_estadoLayout);
        ver_estadoLayout.setHorizontalGroup(
            ver_estadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ver_estadoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ver_estadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel7)
                    .addGroup(ver_estadoLayout.createSequentialGroup()
                        .addGroup(ver_estadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel14)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(ver_estadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Hora_mod_servicio, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Esta_servicio, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(ver_estadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jScrollPane2)
                                .addComponent(Fecha_mod_servicio, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE))
                            .addComponent(Continuar_estado, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        ver_estadoLayout.setVerticalGroup(
            ver_estadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ver_estadoLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel4)
                .addGap(25, 25, 25)
                .addGroup(ver_estadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(Esta_servicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ver_estadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Hora_mod_servicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ver_estadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(Fecha_mod_servicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(ver_estadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ver_estadoLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ver_estadoLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jLabel14)))
                .addGap(18, 18, 18)
                .addComponent(Continuar_estado)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        Seguir_consultas.setTitle("En desarrollo");

        jLabel15.setText("¿Desea consultar el estado de otro servicio?");

        Si_seguir_consul.setText("Sí");
        Si_seguir_consul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Si_seguir_consulActionPerformed(evt);
            }
        });

        No_seguir_consul.setText("No");
        No_seguir_consul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                No_seguir_consulActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Seguir_consultasLayout = new javax.swing.GroupLayout(Seguir_consultas.getContentPane());
        Seguir_consultas.getContentPane().setLayout(Seguir_consultasLayout);
        Seguir_consultasLayout.setHorizontalGroup(
            Seguir_consultasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Seguir_consultasLayout.createSequentialGroup()
                .addContainerGap(102, Short.MAX_VALUE)
                .addComponent(jLabel15)
                .addGap(87, 87, 87))
            .addGroup(Seguir_consultasLayout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addComponent(Si_seguir_consul, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(No_seguir_consul, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68))
        );
        Seguir_consultasLayout.setVerticalGroup(
            Seguir_consultasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Seguir_consultasLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel15)
                .addGap(18, 18, 18)
                .addGroup(Seguir_consultasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Si_seguir_consul)
                    .addComponent(No_seguir_consul))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("En desarrollo");

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel1.setText("<html>Para consultar el estado de un servicio, diligencie al menos dos de los siguentes campos, recuerde que \"Tipo documento\" y \"Número documento\" cuentan como un solo campo");

        Consultar_estado.setText("Consultar");
        Consultar_estado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Consultar_estadoActionPerformed(evt);
            }
        });

        jLabel2.setText("Número del servicio:");

        jLabel3.setText("<html>Fecha en la que se<br>creo el servicio:");

        jLabel5.setText("Tipo documento:");

        Tipo_doc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cédula de ciudadanía", "Cédula de extranjería" }));

        jLabel6.setText("Número documento:");

        Volver.setText("Volver");
        Volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VolverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Num_servicio)
                            .addComponent(Fecha_crea_servicio, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(Volver, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Consultar_estado))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel6)
                                .addComponent(jLabel5))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(18, 18, 18)
                                    .addComponent(Num_doc, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addGap(18, 18, 18)
                                    .addComponent(Tipo_doc, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(Num_servicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Fecha_crea_servicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(Tipo_doc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(Num_doc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Consultar_estado)
                    .addComponent(Volver))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Continuar_estadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Continuar_estadoActionPerformed
        
        Seguir_consultas.setVisible(true);
        
        //Poner en blanco los JTexTField
        Esta_servicio.setText("");
        Fecha_mod_servicio.setText("");
        Hora_mod_servicio.setText("");
        Comentarios_servicio.setText("");
        
    }//GEN-LAST:event_Continuar_estadoActionPerformed

    private void Consultar_estadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Consultar_estadoActionPerformed
        
        this.setVisible(false);
        this.ver_estado.setVisible(true);
        
        //Poner en blanco los JTexTField
        Num_servicio.setText("");
        Fecha_crea_servicio.setText("");
        Num_doc.setText("");
        
    }//GEN-LAST:event_Consultar_estadoActionPerformed

    private void VolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VolverActionPerformed
        
        this.setVisible(false);
        new Menu_Cliente().setVisible(true);
        
    }//GEN-LAST:event_VolverActionPerformed

    private void Si_seguir_consulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Si_seguir_consulActionPerformed

        ver_estado.setVisible(false);
        Seguir_consultas.setVisible(false);
        this.setVisible(true);

    }//GEN-LAST:event_Si_seguir_consulActionPerformed

    private void No_seguir_consulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_No_seguir_consulActionPerformed

        ver_estado.setVisible(false);
        Seguir_consultas.setVisible(false);
        new Menu_Cliente().setVisible(true);

    }//GEN-LAST:event_No_seguir_consulActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Consultar_estado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Consultar_estado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Consultar_estado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Consultar_estado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Consultar_estado().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea Comentarios_servicio;
    private javax.swing.JButton Consultar_estado;
    private javax.swing.JButton Continuar_estado;
    private javax.swing.JTextField Esta_servicio;
    private javax.swing.JTextField Fecha_crea_servicio;
    private javax.swing.JTextField Fecha_mod_servicio;
    private javax.swing.JTextField Hora_mod_servicio;
    private javax.swing.JButton No_seguir_consul;
    private javax.swing.JTextField Num_doc;
    private javax.swing.JTextField Num_servicio;
    private javax.swing.JDialog Seguir_consultas;
    private javax.swing.JButton Si_seguir_consul;
    private javax.swing.JComboBox<String> Tipo_doc;
    private javax.swing.JButton Volver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JFrame ver_estado;
    // End of variables declaration//GEN-END:variables
}
