/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

/**
 *
 * @author Sebastián
 */
public class Consultar_servicio extends javax.swing.JFrame {

    /**
     * Creates new form Consultar_servicio
     */
    public Consultar_servicio() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.Detalles_servicio.setLocationRelativeTo(null);
        this.Detalles_servicio.setSize(340, 500);
        this.Seguir_consultas.setLocationRelativeTo(null);
        this.Seguir_consultas.setSize(450, 155);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Detalles_servicio = new javax.swing.JFrame();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        Hora_crea_servicio = new javax.swing.JTextField();
        est_det_servicio = new javax.swing.JTextField();
        Nom_cli_servicio = new javax.swing.JTextField();
        Fecha_crea_servicio = new javax.swing.JTextField();
        Nom_msj_servicio = new javax.swing.JTextField();
        Tipo_paq_servicio = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        Dir_servicio = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        Descip_servicio = new javax.swing.JTextArea();
        Continuar = new javax.swing.JButton();
        Seguir_consultas = new javax.swing.JDialog();
        jLabel15 = new javax.swing.JLabel();
        Si_seguir_consul = new javax.swing.JButton();
        No_seguir_consul = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Num_servicio = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        Fecha_servicio = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        Num_doc = new javax.swing.JTextField();
        Consultar = new javax.swing.JButton();
        Volver = new javax.swing.JButton();

        Detalles_servicio.setTitle("En desarrollo");

        jLabel4.setText("Los detalles del servicio buscado, son los siguientes:");

        jLabel7.setText("Estado:");

        jLabel8.setText("<html>Hora de creación:");

        jLabel9.setText("Fecha de creación:");

        jLabel10.setText("Mensajero:");

        jLabel11.setText("Cliente:");

        jLabel12.setText("Tipo de paquete:");

        jLabel13.setText("Dirección(es):");

        jLabel14.setText("Descripción:");

        Dir_servicio.setColumns(20);
        Dir_servicio.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        Dir_servicio.setLineWrap(true);
        Dir_servicio.setWrapStyleWord(true);
        jScrollPane1.setViewportView(Dir_servicio);

        Descip_servicio.setColumns(20);
        Descip_servicio.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        Descip_servicio.setLineWrap(true);
        Descip_servicio.setWrapStyleWord(true);
        jScrollPane2.setViewportView(Descip_servicio);

        Continuar.setText("Continuar");
        Continuar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContinuarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Detalles_servicioLayout = new javax.swing.GroupLayout(Detalles_servicio.getContentPane());
        Detalles_servicio.getContentPane().setLayout(Detalles_servicioLayout);
        Detalles_servicioLayout.setHorizontalGroup(
            Detalles_servicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Detalles_servicioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Detalles_servicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Continuar)
                    .addGroup(Detalles_servicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(Detalles_servicioLayout.createSequentialGroup()
                            .addComponent(jLabel10)
                            .addGap(47, 47, 47)
                            .addComponent(Nom_msj_servicio))
                        .addGroup(Detalles_servicioLayout.createSequentialGroup()
                            .addComponent(jLabel9)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(Fecha_crea_servicio))
                        .addComponent(jLabel4)
                        .addGroup(Detalles_servicioLayout.createSequentialGroup()
                            .addGroup(Detalles_servicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel7)
                                .addComponent(jLabel11))
                            .addGap(16, 16, 16)
                            .addGroup(Detalles_servicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(Nom_cli_servicio, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(est_det_servicio, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Hora_crea_servicio, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(Detalles_servicioLayout.createSequentialGroup()
                            .addGroup(Detalles_servicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel12)
                                .addComponent(jLabel13)
                                .addComponent(jLabel14))
                            .addGap(19, 19, 19)
                            .addGroup(Detalles_servicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jScrollPane2)
                                .addComponent(Tipo_paq_servicio)
                                .addComponent(jScrollPane1)))))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        Detalles_servicioLayout.setVerticalGroup(
            Detalles_servicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Detalles_servicioLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel4)
                .addGap(25, 25, 25)
                .addGroup(Detalles_servicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(est_det_servicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(Detalles_servicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(Nom_cli_servicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(Detalles_servicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Hora_crea_servicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(Detalles_servicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(Fecha_crea_servicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Detalles_servicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(Nom_msj_servicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Detalles_servicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(Tipo_paq_servicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Detalles_servicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(Detalles_servicioLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel13)))
                .addGroup(Detalles_servicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Detalles_servicioLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Detalles_servicioLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel14)))
                .addGap(18, 18, 18)
                .addComponent(Continuar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Seguir_consultas.setTitle("En desarrollo");

        jLabel15.setText("¿Desea consultar los detalles de otro servicio?");

        Si_seguir_consul.setText("Sí");
        Si_seguir_consul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Si_seguir_consulActionPerformed(evt);
            }
        });

        No_seguir_consul.setText("No");
        No_seguir_consul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                No_seguir_consulActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Seguir_consultasLayout = new javax.swing.GroupLayout(Seguir_consultas.getContentPane());
        Seguir_consultas.getContentPane().setLayout(Seguir_consultasLayout);
        Seguir_consultasLayout.setHorizontalGroup(
            Seguir_consultasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Seguir_consultasLayout.createSequentialGroup()
                .addContainerGap(93, Short.MAX_VALUE)
                .addComponent(jLabel15)
                .addGap(87, 87, 87))
            .addGroup(Seguir_consultasLayout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addComponent(Si_seguir_consul, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(No_seguir_consul, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68))
        );
        Seguir_consultasLayout.setVerticalGroup(
            Seguir_consultasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Seguir_consultasLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel15)
                .addGap(18, 18, 18)
                .addGroup(Seguir_consultasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Si_seguir_consul)
                    .addComponent(No_seguir_consul))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("En desarrollo");

        jLabel1.setText("<html>Para consultar un servicio, diligencie al menos dos de los siguentes campos");

        jLabel2.setText("Número del servicio:");

        jLabel3.setText("<html>Fecha en la que se<br>creo el servicio:");

        jLabel5.setText("Tipo documento:");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cédula de ciudadanía", "Cédula de extranjería", "Tarjeta de identidad" }));

        jLabel6.setText("Número documento:");

        Consultar.setText("Consultar");
        Consultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConsultarActionPerformed(evt);
            }
        });

        Volver.setText("Volver");
        Volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VolverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Volver, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Consultar))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel5))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Num_doc)
                                    .addComponent(jComboBox1, 0, 140, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Fecha_servicio)
                                    .addComponent(Num_servicio)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(56, 56, 56))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(Num_servicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Fecha_servicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(Num_doc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Consultar)
                    .addComponent(Volver))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Si_seguir_consulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Si_seguir_consulActionPerformed
        
        Detalles_servicio.setVisible(false);
        Seguir_consultas.setVisible(false);
        this.setVisible(true);
        
    }//GEN-LAST:event_Si_seguir_consulActionPerformed

    private void ConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConsultarActionPerformed
        
        this.setVisible(false);
        Detalles_servicio.setVisible(true);
        
        //Poner en blanco todos los JTextField 
        Num_servicio.setText("");
        Fecha_servicio.setText("");
        Num_doc.setText("");
        
    }//GEN-LAST:event_ConsultarActionPerformed

    private void VolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VolverActionPerformed
        
        this.setVisible(false);
        new Menu_Cliente().setVisible(true);
        
    }//GEN-LAST:event_VolverActionPerformed

    private void ContinuarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ContinuarActionPerformed
        
        Seguir_consultas.setVisible(true);
        
        //Poner en blanco todos los JTextField y JTextArea
        est_det_servicio.setText("");
        Nom_cli_servicio.setText("");
        Hora_crea_servicio.setText("");
        Fecha_crea_servicio.setText("");
        Nom_msj_servicio.setText("");
        Tipo_paq_servicio.setText("");
        Dir_servicio.setText("");
        Descip_servicio.setText("");
        
    }//GEN-LAST:event_ContinuarActionPerformed

    private void No_seguir_consulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_No_seguir_consulActionPerformed
        
        Detalles_servicio.setVisible(false);
        Seguir_consultas.setVisible(false);
        new Menu_Cliente().setVisible(true);
        
    }//GEN-LAST:event_No_seguir_consulActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Consultar_servicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Consultar_servicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Consultar_servicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Consultar_servicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Consultar_servicio().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Consultar;
    private javax.swing.JButton Continuar;
    private javax.swing.JTextArea Descip_servicio;
    private javax.swing.JFrame Detalles_servicio;
    private javax.swing.JTextArea Dir_servicio;
    private javax.swing.JTextField Fecha_crea_servicio;
    private javax.swing.JTextField Fecha_servicio;
    private javax.swing.JTextField Hora_crea_servicio;
    private javax.swing.JButton No_seguir_consul;
    private javax.swing.JTextField Nom_cli_servicio;
    private javax.swing.JTextField Nom_msj_servicio;
    private javax.swing.JTextField Num_doc;
    private javax.swing.JTextField Num_servicio;
    private javax.swing.JDialog Seguir_consultas;
    private javax.swing.JButton Si_seguir_consul;
    private javax.swing.JTextField Tipo_paq_servicio;
    private javax.swing.JButton Volver;
    private javax.swing.JTextField est_det_servicio;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
