/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

/**
 *
 * @author Sebastián
 */
public class Inicio extends javax.swing.JFrame {

    /**
     * Creates new form Inicio
     */
    public Inicio() {
        initComponents();
        this.setLocationRelativeTo(null);
        Ventana_cliente.setSize(365, 250);
        Ventana_cliente.setLocationRelativeTo(null);
        Ventana_mensajero.setSize(365, 250);
        Ventana_mensajero.setLocationRelativeTo(null);
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Ventana_cliente = new javax.swing.JFrame();
        jLabel3 = new javax.swing.JLabel();
        Cliente_nuevo = new javax.swing.JButton();
        Cliente_existente = new javax.swing.JButton();
        Volver_cli_inicio = new javax.swing.JButton();
        Ventana_mensajero = new javax.swing.JFrame();
        jLabel4 = new javax.swing.JLabel();
        Mensajero_nuevo = new javax.swing.JButton();
        Mensajero_existente = new javax.swing.JButton();
        Volver_msj_inicio = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        Cliente = new javax.swing.JButton();
        Mensajero = new javax.swing.JButton();
        Admin = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        Ventana_cliente.setTitle("En desarrollo");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("<html>Ha escogido cliente, ¿es usted un cliente nuevo o uno existente?");

        Cliente_nuevo.setText("Nuevo");
        Cliente_nuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cliente_nuevoActionPerformed(evt);
            }
        });

        Cliente_existente.setText("Existente");
        Cliente_existente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cliente_existenteActionPerformed(evt);
            }
        });

        Volver_cli_inicio.setText("Volver");
        Volver_cli_inicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Volver_cli_inicioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Ventana_clienteLayout = new javax.swing.GroupLayout(Ventana_cliente.getContentPane());
        Ventana_cliente.getContentPane().setLayout(Ventana_clienteLayout);
        Ventana_clienteLayout.setHorizontalGroup(
            Ventana_clienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Ventana_clienteLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
            .addGroup(Ventana_clienteLayout.createSequentialGroup()
                .addGroup(Ventana_clienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Ventana_clienteLayout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(Cliente_nuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(61, 61, 61)
                        .addComponent(Cliente_existente, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Ventana_clienteLayout.createSequentialGroup()
                        .addGap(145, 145, 145)
                        .addComponent(Volver_cli_inicio, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(56, Short.MAX_VALUE))
        );
        Ventana_clienteLayout.setVerticalGroup(
            Ventana_clienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Ventana_clienteLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(Ventana_clienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Cliente_nuevo)
                    .addComponent(Cliente_existente))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(Volver_cli_inicio)
                .addGap(27, 27, 27))
        );

        Ventana_mensajero.setTitle("En desarrollo");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("<html>Ha escogido mensajero, ¿es usted un mensajero nuevo o uno existente?");

        Mensajero_nuevo.setText("Nuevo");
        Mensajero_nuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Mensajero_nuevoActionPerformed(evt);
            }
        });

        Mensajero_existente.setText("Existente");
        Mensajero_existente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Mensajero_existenteActionPerformed(evt);
            }
        });

        Volver_msj_inicio.setText("Volver");
        Volver_msj_inicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Volver_msj_inicioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Ventana_mensajeroLayout = new javax.swing.GroupLayout(Ventana_mensajero.getContentPane());
        Ventana_mensajero.getContentPane().setLayout(Ventana_mensajeroLayout);
        Ventana_mensajeroLayout.setHorizontalGroup(
            Ventana_mensajeroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Ventana_mensajeroLayout.createSequentialGroup()
                .addGroup(Ventana_mensajeroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Ventana_mensajeroLayout.createSequentialGroup()
                        .addGap(145, 145, 145)
                        .addComponent(Volver_msj_inicio, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Ventana_mensajeroLayout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(Ventana_mensajeroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(Ventana_mensajeroLayout.createSequentialGroup()
                                .addComponent(Mensajero_nuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(61, 61, 61)
                                .addComponent(Mensajero_existente, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        Ventana_mensajeroLayout.setVerticalGroup(
            Ventana_mensajeroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Ventana_mensajeroLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(Ventana_mensajeroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Mensajero_nuevo)
                    .addComponent(Mensajero_existente))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Volver_msj_inicio)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("En desarrollo");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Bienvenido/a");

        Cliente.setText("Cliente");
        Cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClienteActionPerformed(evt);
            }
        });

        Mensajero.setText("Mensajero");
        Mensajero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MensajeroActionPerformed(evt);
            }
        });

        Admin.setText("Administrador");
        Admin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdminActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("¿Comó usara la aplicación el día de hoy?");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Admin)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Mensajero, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addComponent(jLabel1)))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Mensajero)
                    .addComponent(Cliente)
                    .addComponent(Admin))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Cliente_nuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cliente_nuevoActionPerformed
        
        Ventana_cliente.setVisible(false);
        new Registro_Cliente().setVisible(true);
        
    }//GEN-LAST:event_Cliente_nuevoActionPerformed

    private void ClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClienteActionPerformed
        
        this.setVisible(false);
        Ventana_cliente.setVisible(true);
        
    }//GEN-LAST:event_ClienteActionPerformed

    private void Cliente_existenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cliente_existenteActionPerformed
        
        Ventana_cliente.setVisible(false);
        new Menu_Cliente().setVisible(true);
        
    }//GEN-LAST:event_Cliente_existenteActionPerformed

    private void Volver_cli_inicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Volver_cli_inicioActionPerformed
        
        Ventana_cliente.setVisible(false);
        this.setVisible(true);
        
    }//GEN-LAST:event_Volver_cli_inicioActionPerformed

    private void Mensajero_nuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Mensajero_nuevoActionPerformed
        
        Ventana_mensajero.setVisible(false);
        new Registro_Mensajero().setVisible(true);
        
    }//GEN-LAST:event_Mensajero_nuevoActionPerformed

    private void Mensajero_existenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Mensajero_existenteActionPerformed
        
    }//GEN-LAST:event_Mensajero_existenteActionPerformed

    private void Volver_msj_inicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Volver_msj_inicioActionPerformed
       
        Ventana_mensajero.setVisible(false);
        this.setVisible(true);
    }//GEN-LAST:event_Volver_msj_inicioActionPerformed

    private void AdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdminActionPerformed
        
        this.setVisible(false);
        new Administrador().setVisible(true);
        
    }//GEN-LAST:event_AdminActionPerformed

    private void MensajeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MensajeroActionPerformed
        
        this.setVisible(false);
        Ventana_mensajero.setVisible(true);
        
    }//GEN-LAST:event_MensajeroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Admin;
    private javax.swing.JButton Cliente;
    private javax.swing.JButton Cliente_existente;
    private javax.swing.JButton Cliente_nuevo;
    private javax.swing.JButton Mensajero;
    private javax.swing.JButton Mensajero_existente;
    private javax.swing.JButton Mensajero_nuevo;
    private javax.swing.JFrame Ventana_cliente;
    private javax.swing.JFrame Ventana_mensajero;
    private javax.swing.JButton Volver_cli_inicio;
    private javax.swing.JButton Volver_msj_inicio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
