/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import Controlador.Controlador;
import Controlador.Mensajero;
import Controlador.TelefonoMensajero;
import Controlador.CorreoMensajero;
import Controlador.Jornada;

/**
 *
 * @author Sebastián
 */
public class Registro_Mensajero extends javax.swing.JFrame {
    
    private Controlador controlador = new Controlador();
    private Mensajero mensajero;
    private TelefonoMensajero telMensajero;
    private CorreoMensajero correoMensajero;
    private Jornada jornada;
    

    /**
     * Creates new form Registro_Mensajero
     */
    public Registro_Mensajero() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.Aviso_registro_msj.setLocationRelativeTo(null);
        this.Aviso_registro_msj.setSize(450, 155);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Aviso_registro_msj = new javax.swing.JDialog();
        jLabel14 = new javax.swing.JLabel();
        Conti_aviso_msj = new javax.swing.JButton();
        Panel_mensajero = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        Pri_ape_msj = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        Seg_ape_msj = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        Tipo_doc_msj = new javax.swing.JComboBox<>();
        Pri_nom_msj = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Seg_nom_msj = new javax.swing.JTextField();
        Num_doc_msj = new javax.swing.JTextField();
        Conti_panel1_msj = new javax.swing.JButton();
        Salir_msj = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        Fecha_nac_msj = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        Nac_msj = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        Segu_soc_msj = new javax.swing.JComboBox<>();
        Conti_panel2_msj = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        Sexo_nsj = new javax.swing.JComboBox<>();
        Atras1 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tel_msj = new javax.swing.JTextArea();
        jLabel20 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Cor_msj = new javax.swing.JTextArea();
        Conti_panel3_msj = new javax.swing.JButton();
        Atras2 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        Conti_panel4_msj = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        Lunes_check = new javax.swing.JCheckBox();
        Martes_check = new javax.swing.JCheckBox();
        Miercoles_check = new javax.swing.JCheckBox();
        Jueves_check = new javax.swing.JCheckBox();
        Viernes_check = new javax.swing.JCheckBox();
        Sabado_check = new javax.swing.JCheckBox();
        Domingo_check = new javax.swing.JCheckBox();
        jLabel18 = new javax.swing.JLabel();
        Hora_ini_lunes = new javax.swing.JTextField();
        Hora_fin_lunes = new javax.swing.JTextField();
        Hora_ini_martes = new javax.swing.JTextField();
        Hora_fin_martes = new javax.swing.JTextField();
        Hora_ini_miercoles = new javax.swing.JTextField();
        Hora_ini_jueves = new javax.swing.JTextField();
        Hora_ini_viernes = new javax.swing.JTextField();
        Hora_ini_sabado = new javax.swing.JTextField();
        Hora_ini_domingo = new javax.swing.JTextField();
        Hora_fin_miercoles = new javax.swing.JTextField();
        Hora_fin_jueves = new javax.swing.JTextField();
        Hora_fin_viernes = new javax.swing.JTextField();
        Hora_fin_sabado = new javax.swing.JTextField();
        Hora_fin_domingo = new javax.swing.JTextField();
        Atras3 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        Tipo_veh_msj = new javax.swing.JComboBox<>();
        Regis_msj = new javax.swing.JButton();
        Tipo_trans_msj = new javax.swing.JComboBox<>();
        Atras4 = new javax.swing.JButton();

        Aviso_registro_msj.setTitle("En desarrollo");

        jLabel14.setText("Registro exitoso, habilitada opción de atender servicio");

        Conti_aviso_msj.setText("Continuar");
        Conti_aviso_msj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Conti_aviso_msjActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Aviso_registro_msjLayout = new javax.swing.GroupLayout(Aviso_registro_msj.getContentPane());
        Aviso_registro_msj.getContentPane().setLayout(Aviso_registro_msjLayout);
        Aviso_registro_msjLayout.setHorizontalGroup(
            Aviso_registro_msjLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Aviso_registro_msjLayout.createSequentialGroup()
                .addGroup(Aviso_registro_msjLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Aviso_registro_msjLayout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(jLabel14))
                    .addGroup(Aviso_registro_msjLayout.createSequentialGroup()
                        .addGap(159, 159, 159)
                        .addComponent(Conti_aviso_msj)))
                .addContainerGap(69, Short.MAX_VALUE))
        );
        Aviso_registro_msjLayout.setVerticalGroup(
            Aviso_registro_msjLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Aviso_registro_msjLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel14)
                .addGap(18, 18, 18)
                .addComponent(Conti_aviso_msj)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("En desarrollo");

        jLabel3.setText("Primer apellido:");

        jLabel4.setText("Segundo apellido:");

        jLabel5.setText("Tipo documento:");

        jLabel1.setText("Primer nombre:");

        Tipo_doc_msj.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cédula de ciudadanía", "Cédula de extranjería", "Tarjeta de identidad" }));

        jLabel6.setText("Número documento:");

        jLabel2.setText("Segundo nombre:");

        Conti_panel1_msj.setText("Continuar");
        Conti_panel1_msj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Conti_panel1_msjActionPerformed(evt);
            }
        });

        Salir_msj.setText("Salir");
        Salir_msj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Salir_msjActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Salir_msj, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Conti_panel1_msj))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(Num_doc_msj))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Pri_ape_msj, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2))
                                .addGap(32, 32, 32)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(Pri_nom_msj, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Seg_nom_msj, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(Seg_ape_msj, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Tipo_doc_msj, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(59, 59, 59))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(Pri_nom_msj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(Seg_nom_msj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(Pri_ape_msj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(Seg_ape_msj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(Tipo_doc_msj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(Num_doc_msj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Conti_panel1_msj)
                    .addComponent(Salir_msj))
                .addGap(35, 35, 35))
        );

        Panel_mensajero.addTab("Básicos", jPanel1);

        jLabel7.setText("Fecha de nacimiento:");

        jLabel8.setText("Nacionalidad:");

        jLabel10.setText("Seguridad social:");

        Segu_soc_msj.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sí", "No" }));

        Conti_panel2_msj.setText("Continuar");
        Conti_panel2_msj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Conti_panel2_msjActionPerformed(evt);
            }
        });

        jLabel12.setText("Sexo:");

        Sexo_nsj.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "F", "M" }));

        Atras1.setText("Atras");
        Atras1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Atras1ActionPerformed(evt);
            }
        });

        jLabel9.setText("<html> Recuerde el formato de la fecha DD/MM/YYYY, p. ej. 24/08/2020.");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(Atras1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Conti_panel2_msj)
                        .addGap(59, 59, 59))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel12))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(Segu_soc_msj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(Fecha_nac_msj)
                                        .addComponent(Nac_msj, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(Sexo_nsj, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(40, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(Fecha_nac_msj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(Nac_msj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(Segu_soc_msj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(Sexo_nsj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Conti_panel2_msj)
                    .addComponent(Atras1))
                .addGap(35, 35, 35))
        );

        Panel_mensajero.addTab("Básicos 2", jPanel2);

        jLabel19.setText("Télefono(s):");

        Tel_msj.setColumns(20);
        Tel_msj.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        Tel_msj.setRows(3);
        jScrollPane1.setViewportView(Tel_msj);

        jLabel20.setText("<html>Correo(s) electronico(s):");

        Cor_msj.setColumns(20);
        Cor_msj.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        Cor_msj.setRows(4);
        jScrollPane2.setViewportView(Cor_msj);

        Conti_panel3_msj.setText("Continuar");
        Conti_panel3_msj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Conti_panel3_msjActionPerformed(evt);
            }
        });

        Atras2.setText("Atras");
        Atras2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Atras2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel19))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                            .addComponent(jScrollPane2))
                        .addContainerGap(73, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(Atras2, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Conti_panel3_msj)
                        .addGap(59, 59, 59))))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(jLabel19)))
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Conti_panel3_msj)
                    .addComponent(Atras2))
                .addGap(35, 35, 35))
        );

        Panel_mensajero.addTab("Contacto", jPanel5);

        Conti_panel4_msj.setText("Continuar");
        Conti_panel4_msj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Conti_panel4_msjActionPerformed(evt);
            }
        });

        jLabel15.setText("Día");

        jLabel16.setText("Hora inicio");

        jLabel17.setText("Hora final");

        Lunes_check.setText("Lunes");

        Martes_check.setText("Martes");

        Miercoles_check.setText("Miércoles");

        Jueves_check.setText("Jueves");

        Viernes_check.setText("Viernes");

        Sabado_check.setText("Sábado");

        Domingo_check.setText("Domingo");

        jLabel18.setText("Recuerde que el formato de la hora es el de 24h, p. ej. 18:15");

        Atras3.setText("Atras");
        Atras3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Atras3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(Atras3, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Conti_panel4_msj)
                        .addGap(59, 59, 59))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(jLabel15)
                                .addGap(33, 33, 33))
                            .addComponent(Domingo_check)
                            .addComponent(Lunes_check)
                            .addComponent(Martes_check)
                            .addComponent(Miercoles_check)
                            .addComponent(Jueves_check)
                            .addComponent(Viernes_check)
                            .addComponent(Sabado_check))
                        .addGap(50, 50, 50)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Hora_ini_viernes)
                            .addComponent(Hora_ini_sabado)
                            .addComponent(Hora_ini_domingo)
                            .addComponent(Hora_ini_lunes)
                            .addComponent(Hora_ini_miercoles)
                            .addComponent(Hora_ini_jueves)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addGap(0, 11, Short.MAX_VALUE))
                            .addComponent(Hora_ini_martes))
                        .addGap(72, 72, 72)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel17)
                            .addComponent(Hora_fin_lunes, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                            .addComponent(Hora_fin_martes)
                            .addComponent(Hora_fin_miercoles)
                            .addComponent(Hora_fin_jueves)
                            .addComponent(Hora_fin_viernes)
                            .addComponent(Hora_fin_sabado)
                            .addComponent(Hora_fin_domingo))
                        .addGap(53, 53, 53))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Hora_fin_lunes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addComponent(Hora_fin_martes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addComponent(Hora_fin_miercoles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Hora_fin_jueves, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addComponent(Hora_fin_viernes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addComponent(Hora_fin_sabado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(jLabel16))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Lunes_check)
                            .addComponent(Hora_ini_lunes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Martes_check)
                            .addComponent(Hora_ini_martes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Miercoles_check)
                            .addComponent(Hora_ini_miercoles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Jueves_check)
                            .addComponent(Hora_ini_jueves, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Viernes_check)
                            .addComponent(Hora_ini_viernes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Sabado_check)
                            .addComponent(Hora_ini_sabado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Domingo_check)
                            .addComponent(Hora_ini_domingo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Hora_fin_domingo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(7, 7, 7)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Conti_panel4_msj)
                    .addComponent(Atras3))
                .addContainerGap())
        );

        Panel_mensajero.addTab("Horario", jPanel4);

        jLabel11.setText("Tipo:");

        jLabel13.setText("Transporte:");

        Tipo_veh_msj.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Moto", "Bicicleta", "Carro" }));

        Regis_msj.setText("Registrar");
        Regis_msj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Regis_msjActionPerformed(evt);
            }
        });

        Tipo_trans_msj.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Documento", "Paquete pequeño", "Paquete mediano", "Paquete grande" }));

        Atras4.setText("Atras");
        Atras4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Atras4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(Atras4, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 141, Short.MAX_VALUE)
                        .addComponent(Regis_msj)
                        .addGap(59, 59, 59))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addGap(51, 51, 51))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addGap(18, 18, 18)))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Tipo_veh_msj, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Tipo_trans_msj, 0, 140, Short.MAX_VALUE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(Tipo_veh_msj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(Tipo_trans_msj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Regis_msj)
                    .addComponent(Atras4))
                .addGap(35, 35, 35))
        );

        Panel_mensajero.addTab("Vehiculo", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel_mensajero)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel_mensajero)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Conti_panel1_msjActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Conti_panel1_msjActionPerformed
        
        Panel_mensajero.setSelectedIndex(1);
        
    }//GEN-LAST:event_Conti_panel1_msjActionPerformed

    private void Conti_panel2_msjActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Conti_panel2_msjActionPerformed
       
        Panel_mensajero.setSelectedIndex(2);
        
    }//GEN-LAST:event_Conti_panel2_msjActionPerformed

    private void Conti_panel4_msjActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Conti_panel4_msjActionPerformed
       
        Panel_mensajero.setSelectedIndex(4);
        
    }//GEN-LAST:event_Conti_panel4_msjActionPerformed

    private void Regis_msjActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Regis_msjActionPerformed
        
        
         try{
            mensajero = controlador.getMensajero();
            mensajero.setPrimNombre(Pri_nom_msj.getText());
            mensajero.setSegNombre(Seg_nom_msj.getText());
            mensajero.setPrimApellido(Pri_ape_msj.getText());
            mensajero.setSegApellido(Seg_ape_msj.getText());
            mensajero.setNumeroDeDocumento(Integer.valueOf(Num_doc_msj.getText()));
            mensajero.setFechaDeNacimiento(Fecha_nac_msj.getText());
            mensajero.setNacionalidad(Nac_msj.getText());
            String tipo_documento = Tipo_doc_msj.getSelectedItem().toString();
            if (tipo_documento == "Cédula de ciudadanía"){
                tipo_documento = "C.C";
            } else if(tipo_documento == "Cédula de extranjería"){
                tipo_documento = "C.E";
            } else if(tipo_documento == "Tarjeta de identidad"){
                tipo_documento = "T.I";
            }
            mensajero.setTipoDeDocumento(tipo_documento);
            String segSocial = Segu_soc_msj.getSelectedItem().toString();
            
            if (segSocial == "Sí"){
                segSocial = "SI";
            } else if(segSocial == "No"){
                segSocial = "NO";
            }
            mensajero.setSeguridadSocial(segSocial);
            mensajero.setMedioDeTransporte(Tipo_veh_msj.getSelectedItem().toString());
            mensajero.setSexo(Sexo_nsj.getSelectedItem().toString());
            mensajero.setTipoDeTransporte(Tipo_trans_msj.getSelectedItem().toString());
            mensajero.setEstado("SI");
            
        //    controlador.InsertarMensajero();
            String telefonos []= Tel_msj.getText().split("-");
            String correos[] = Cor_msj.getText().split("-");
            for (int i = 0 ; i < telefonos.length ; i ++){
                telMensajero = controlador.getTelefonoMensajero();
                telMensajero.setTelefonoMensajero(Integer.valueOf(telefonos[i]));
                telMensajero.setTipoDocumento(mensajero.getTipoDeDocumento());
                telMensajero.setNumeroDocumento(mensajero.getNumeroDeDocumento());
         //       controlador.InsertarTelefonoMensajero();
            }
            for (int i = 0 ; i < correos.length ; i ++){
                correoMensajero = controlador.getCorreoMensajero();
                correoMensajero.setCorreoMenjajero(correos[i]);
                correoMensajero.setTipoDocumento(mensajero.getTipoDeDocumento());
                correoMensajero.setNumeroDocumento(mensajero.getNumeroDeDocumento());
         //       controlador.InsertarCorreoMensajero();
            }
            
            
            if (Lunes_check.isSelected()){
                jornada = controlador.getJornada();
                jornada.setDia("Lunes");
                jornada.setTipoDocumento(mensajero.getTipoDeDocumento());
                jornada.setNumeroDocumento(mensajero.getNumeroDeDocumento());
                jornada.setHoraInicial(Hora_ini_lunes.getText());
                jornada.setHoraInicial(Hora_fin_lunes.getText());
                
                controlador.InsertarJornada();
            }
            if (Martes_check.isSelected()){
                jornada = controlador.getJornada();
                jornada.setDia("Martes");
                jornada.setTipoDocumento(mensajero.getTipoDeDocumento());
                jornada.setNumeroDocumento(mensajero.getNumeroDeDocumento());
                jornada.setHoraInicial(Hora_ini_martes.getText());
                jornada.setHoraInicial(Hora_fin_martes.getText());
                
                controlador.InsertarJornada();
            }
            if (Miercoles_check.isSelected()){
                jornada = controlador.getJornada();
                jornada.setDia("Miercoles");
                jornada.setTipoDocumento(mensajero.getTipoDeDocumento());
                jornada.setNumeroDocumento(mensajero.getNumeroDeDocumento());
                jornada.setHoraInicial(Hora_ini_miercoles.getText());
                jornada.setHoraInicial(Hora_fin_miercoles.getText());
                
                controlador.InsertarJornada();
            }
            if (Jueves_check.isSelected()){
                jornada = controlador.getJornada();
                jornada.setDia("Jueves");
                jornada.setTipoDocumento(mensajero.getTipoDeDocumento());
                jornada.setNumeroDocumento(mensajero.getNumeroDeDocumento());
                jornada.setHoraInicial(Hora_ini_jueves.getText());
                jornada.setHoraInicial(Hora_fin_jueves.getText());
                
                controlador.InsertarJornada();
            }
            if (Viernes_check.isSelected()){
                jornada = controlador.getJornada();
                jornada.setDia("Viernes");
                jornada.setTipoDocumento(mensajero.getTipoDeDocumento());
                jornada.setNumeroDocumento(mensajero.getNumeroDeDocumento());
                jornada.setHoraInicial(Hora_ini_viernes.getText());
                jornada.setHoraInicial(Hora_fin_viernes.getText());
                
                controlador.InsertarJornada();
            }
            if (Sabado_check.isSelected()){
                jornada = controlador.getJornada();
                jornada.setDia("Sabado");
                jornada.setTipoDocumento(mensajero.getTipoDeDocumento());
                jornada.setNumeroDocumento(mensajero.getNumeroDeDocumento());
                jornada.setHoraInicial(Hora_ini_sabado.getText());
                jornada.setHoraInicial(Hora_fin_sabado.getText());
                
                controlador.InsertarJornada();
            }
            if (Domingo_check.isSelected()){
                jornada = controlador.getJornada();
                jornada.setDia("Domingo");
                jornada.setTipoDocumento(mensajero.getTipoDeDocumento());
                jornada.setNumeroDocumento(mensajero.getNumeroDeDocumento());
                jornada.setHoraInicial(Hora_ini_domingo.getText());
                jornada.setHoraInicial(Hora_fin_domingo.getText());
                
                controlador.InsertarJornada();
            }
            Aviso_registro_msj.setVisible(true);
            
            
        }catch(Exception e){
            System.out.println(e);
        }

        //Poner en blanco todos los JTextField y los JCheckBox
        Pri_nom_msj.setText("");
        Seg_nom_msj.setText("");
        Pri_ape_msj.setText("");
        Seg_ape_msj.setText("");
        Num_doc_msj.setText("");
        Fecha_nac_msj.setText("");
        Nac_msj.setText("");
        Lunes_check.setSelected(false);
        Martes_check.setSelected(false);
        Miercoles_check.setSelected(false);
        Jueves_check.setSelected(false);
        Viernes_check.setSelected(false);
        Sabado_check.setSelected(false);
        Domingo_check.setSelected(false);
        Hora_ini_lunes.setText("");
        Hora_fin_lunes.setText("");
        Hora_ini_martes.setText("");
        Hora_fin_martes.setText("");
        Hora_ini_miercoles.setText("");
        Hora_fin_miercoles.setText("");
        Hora_ini_jueves.setText("");
        Hora_fin_jueves.setText("");
        Hora_ini_viernes.setText("");
        Hora_fin_viernes.setText("");
        Hora_ini_sabado.setText("");
        Hora_fin_sabado.setText("");
        Hora_ini_domingo.setText("");
        Hora_fin_domingo.setText("");
        
    }//GEN-LAST:event_Regis_msjActionPerformed

    private void Conti_aviso_msjActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Conti_aviso_msjActionPerformed
        
        this.setVisible(false);
        Aviso_registro_msj.setVisible(false);
        new Inicio().setVisible(true);
        
    }//GEN-LAST:event_Conti_aviso_msjActionPerformed

    private void Salir_msjActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Salir_msjActionPerformed
        
        this.setVisible(false);
        new Inicio().setVisible(true);
        
    }//GEN-LAST:event_Salir_msjActionPerformed

    private void Atras1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Atras1ActionPerformed
        
       Panel_mensajero.setSelectedIndex(0); 
        
    }//GEN-LAST:event_Atras1ActionPerformed

    private void Atras3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Atras3ActionPerformed
        
        Panel_mensajero.setSelectedIndex(2);
        
    }//GEN-LAST:event_Atras3ActionPerformed

    private void Atras4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Atras4ActionPerformed
        
        Panel_mensajero.setSelectedIndex(3);
        
    }//GEN-LAST:event_Atras4ActionPerformed

    private void Conti_panel3_msjActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Conti_panel3_msjActionPerformed
        
        Panel_mensajero.setSelectedIndex(3);
        
    }//GEN-LAST:event_Conti_panel3_msjActionPerformed

    private void Atras2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Atras2ActionPerformed
        
        Panel_mensajero.setSelectedIndex(1);
        
    }//GEN-LAST:event_Atras2ActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Registro_Mensajero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Registro_Mensajero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Registro_Mensajero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Registro_Mensajero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Registro_Mensajero().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Atras1;
    private javax.swing.JButton Atras2;
    private javax.swing.JButton Atras3;
    private javax.swing.JButton Atras4;
    private javax.swing.JDialog Aviso_registro_msj;
    private javax.swing.JButton Conti_aviso_msj;
    private javax.swing.JButton Conti_panel1_msj;
    private javax.swing.JButton Conti_panel2_msj;
    private javax.swing.JButton Conti_panel3_msj;
    private javax.swing.JButton Conti_panel4_msj;
    private javax.swing.JTextArea Cor_msj;
    private javax.swing.JCheckBox Domingo_check;
    private javax.swing.JTextField Fecha_nac_msj;
    private javax.swing.JTextField Hora_fin_domingo;
    private javax.swing.JTextField Hora_fin_jueves;
    private javax.swing.JTextField Hora_fin_lunes;
    private javax.swing.JTextField Hora_fin_martes;
    private javax.swing.JTextField Hora_fin_miercoles;
    private javax.swing.JTextField Hora_fin_sabado;
    private javax.swing.JTextField Hora_fin_viernes;
    private javax.swing.JTextField Hora_ini_domingo;
    private javax.swing.JTextField Hora_ini_jueves;
    private javax.swing.JTextField Hora_ini_lunes;
    private javax.swing.JTextField Hora_ini_martes;
    private javax.swing.JTextField Hora_ini_miercoles;
    private javax.swing.JTextField Hora_ini_sabado;
    private javax.swing.JTextField Hora_ini_viernes;
    private javax.swing.JCheckBox Jueves_check;
    private javax.swing.JCheckBox Lunes_check;
    private javax.swing.JCheckBox Martes_check;
    private javax.swing.JCheckBox Miercoles_check;
    private javax.swing.JTextField Nac_msj;
    private javax.swing.JTextField Num_doc_msj;
    private javax.swing.JTabbedPane Panel_mensajero;
    private javax.swing.JTextField Pri_ape_msj;
    private javax.swing.JTextField Pri_nom_msj;
    private javax.swing.JButton Regis_msj;
    private javax.swing.JCheckBox Sabado_check;
    private javax.swing.JButton Salir_msj;
    private javax.swing.JTextField Seg_ape_msj;
    private javax.swing.JTextField Seg_nom_msj;
    private javax.swing.JComboBox<String> Segu_soc_msj;
    private javax.swing.JComboBox<String> Sexo_nsj;
    private javax.swing.JTextArea Tel_msj;
    private javax.swing.JComboBox<String> Tipo_doc_msj;
    private javax.swing.JComboBox<String> Tipo_trans_msj;
    private javax.swing.JComboBox<String> Tipo_veh_msj;
    private javax.swing.JCheckBox Viernes_check;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
