/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 15.1 		*/
/*  Created On : 21-ago.-2020 2:11:25 p. m. 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Tables */

DROP TABLE IF EXISTS "Categoria" CASCADE
;

DROP TABLE IF EXISTS "Ciudad" CASCADE
;

DROP TABLE IF EXISTS "Cliente" CASCADE
;

DROP TABLE IF EXISTS "Cliente" CASCADE
;

DROP TABLE IF EXISTS "Correo_Cliente" CASCADE
;

DROP TABLE IF EXISTS "Correo_Cliente" CASCADE
;

DROP TABLE IF EXISTS "Correo_mensajero" CASCADE
;

DROP TABLE IF EXISTS "Estado" CASCADE
;

DROP TABLE IF EXISTS "Jornada" CASCADE
;

DROP TABLE IF EXISTS "Mensajero" CASCADE
;

DROP TABLE IF EXISTS "Producto" CASCADE
;

DROP TABLE IF EXISTS "Servicio" CASCADE
;

DROP TABLE IF EXISTS "Telefono_Cliente" CASCADE
;

DROP TABLE IF EXISTS "Telefono_Cliente" CASCADE
;

DROP TABLE IF EXISTS "Telefono_mensajero" CASCADE
;

DROP TABLE IF EXISTS "Trayecto" CASCADE
;

/* Create Tables */

CREATE TABLE "Categoria"
(
	id_categoria integer NOT NULL,	-- Este atributo ayuda a diferenciar una categoria de otra , la cual servira para clasificar cada producto.
	nombre varchar(25) NOT NULL,	-- Es el nombre que se le da a la categoria, ej: Shampoo, smartphone, etc.
	descripcion varchar(70) NOT NULL	-- Hace referencia a la descripción de cada categoria.
)
;

CREATE TABLE "Ciudad"
(
	k_codigo_postal numeric(5) NOT NULL,
	n_nombre varchar(30) NOT NULL,
	v_costo_por_trayecto numeric(10,2) NOT NULL
)
;

CREATE TABLE "Cliente"
(
	k_tipo_documento varchar(2) NOT NULL,
	k_numero_documento numeric(10) NOT NULL,
	n_primer_nombre varchar(20) NOT NULL,	-- Primer del nombre del usuario quien hace uso del servicio. 
	n_segundo_nombre varchar(20) NULL,	-- Segundo nombre del usuario quien hace uso del servicio. 
	n_primer_apellido varchar(20) NOT NULL,	-- Primer del apellido del usuario quien hace uso del servicio.
	n_segundo_apellido varchar(20) NULL,	-- Segundo apellido del usuario quien hace uso del servicio.
	o_calle varchar(20) NOT NULL,
	v_numero numeric(3) NOT NULL,
	o_ciudad varchar(30) NOT NULL,
	o_barrio varchar(30) NOT NULL
)
;

CREATE TABLE "Cliente"
(
	k_tipo_documento varchar(2) NOT NULL,	-- Tipo de documento de indentificación del cliente(CC , TI, CE, pasaporte).
	k_numero_documento numeric(10) NULL,
	n_primer_nombre varchar(20) NOT NULL,	-- Primer del nombre del usuario quien hace uso del servicio. 
	n_segundo_nombre varchar(20) NULL,	-- Segundo del nombre del usuario quien hace uso del servicio.
	n_primer_apellido varchar(20) NOT NULL,	-- Primer del apellido del usuario quien hace uso del servicio.
	n_segundo_apellido varchar(20) NULL,	-- Segundodel apellido del usuario quien hace uso del servicio.
	o_calle varchar(20) NOT NULL,
	v_numero numeric(3) NOT NULL,
	o_ciudad varchar(30) NOT NULL,
	o_barrio varchar(30) NOT NULL
)
;

CREATE TABLE "Correo_Cliente"
(
	k_correo_cliente varchar(30) NOT NULL,
	k_tipo_documento varchar(2) NOT NULL,
	k_numero_documento numeric(10) NOT NULL
)
;

CREATE TABLE "Correo_Cliente"
(
	k_correo_cliente varchar(30) NOT NULL,
	k_tipo_documento varchar(2) NOT NULL,
	k_numero_documento numeric(10) NOT NULL
)
;

CREATE TABLE "Correo_mensajero"
(
	k_correo_elect_mensajero varchar(30) NOT NULL,	-- Dirección(es) de correo electronico que puede llegar a tener el mensajero.
	k_tipo_documento varchar(2) NOT NULL,
	k_numero_documento numeric(10) NOT NULL
)
;

CREATE TABLE "Estado"
(
	k_id_servicio integer NOT NULL,
	k_estado_servicio varchar(9) NOT NULL,	-- Hace referencia a los 3 posibles estados en que se pueda encontrar el servicio (iniciado, cancelado, terminado). 
	f_cambio_estado date NOT NULL,
	n_descripcion varchar(200) NOT NULL
)
;

CREATE TABLE "Jornada"
(
	k_dia varchar(9) NOT NULL,	-- Día de la semana en que se dearrolla la jornada del mensajero.
	k_tipo_documento varchar(2) NOT NULL,	-- Tipo de documento de indentificación del mensajero (CC , TI, CE, pasaporte).
	k_numero_documento numeric(10) NOT NULL,	-- Numero de identificación del documento del mensajero.
	o_hora_inicial varchar(5) NOT NULL,	-- Hora en que empieza la jornada del mensajero.
	o_hora_final varchar(5) NOT NULL	-- Hora en la que finaliza la jornada del mensajero. 
)
;

CREATE TABLE "Mensajero"
(
	k_tipo_documento varchar(2) NOT NULL,	-- Tipo de documento de indentificación del mensajero (CC , TI, CE, pasaporte).
	k_numero_documento numeric(10) NOT NULL,	-- Número de identificación del documento del mensajero.
	v_calificacion_promedio numeric(2,1) NULL,	-- Sumatoria de la puntuación de cada calificación entre el numero de calificaciones hechas por los clientes. 
	i_sexo char(1) NOT NULL,	-- Segundo nombre del mensajero.
	n_nacionalidad varchar(20) NOT NULL,	-- Nación, territorio en el que nació el mensajero.
	f_nacimiento date NOT NULL,
	i_seguridad_social char(2) NOT NULL,	-- Protección que se le proporciona al mensajero para asegurar el acceso a la asistencia médica y garantizar la seguridad del ingreso.
	n_tipo_medio_transporte varchar(9) NOT NULL,	-- Tipo de transporte a serivico del mensajero, el cual puede ser en moto o bicicleta.
	v_pago_acumulado numeric(10,2) NULL,
	n_tipo_transporte varchar(50) NOT NULL,	-- Tipo de paquete transportado (un documento, un paquete pequeño, mediano o grande).
	i_estado char(2) NOT NULL	-- Disponibilidad
)
;

CREATE TABLE "Producto"
(
	id_producto numeric(20) NOT NULL,	-- Este atrivuto identifica de forma unica cada producto.
	nombre varchar(20) NOT NULL,	-- Este nombre representa el nombre del producto.
	precio_actual numeric(7,2) NOT NULL,	-- Hace referencia al precio que actualmente se maneja para el producto por parte del proveedor.
	stock integer NULL,	-- Hace referencia a la cantidad disponible de este producto, el valor de este puede variar.
	num_id_proveedor varchar(17) NOT NULL,
	tipo_id_proveedor varchar(3) NOT NULL,
	id_categoria integer NOT NULL,
	cantidad_producto smallint NULL,	-- Hace referencia a la cantidad que se compra de un producto
	precio_venta numeric(9,2) NOT NULL,	-- Hace referencia al precio que se le da al producto al momento de venderlo
	monto_producto numeric(8,2) NULL,	-- Hace referencia al costo total de una misma cantidad de productos
	id_venta numeric(12) NOT NULL	-- Hace referencia a la identificación de la venta.
)
;

CREATE TABLE "Servicio"
(
	k_id_servicio integer NOT NULL,
	q_cantidad_trayectos integer NOT NULL,
	n_tipo_transporte varchar(14) NOT NULL,	-- Tipo de paquete transportado (un documento, un paquete pequeño, mediano o grande).
	i_tipo_ida_vuelta char(2) NOT NULL,	-- Indica si el servicio es de ida y vuelta, para los casos en que el mensajero tiene que volver al punto de partida. 
	f_inicio date NOT NULL,
	o_hora_inicio time(5) without time zone NOT NULL,
	q_comision integer NOT NULL,
	v_costo_total numeric(10,2) NOT NULL,
	v_calificacion integer NOT NULL,
	k_codigo_postal numeric(5) NOT NULL,
	k_tipo_documento varchar(2) NOT NULL,
	k_numero_documento numeric(10) NOT NULL,
	k_tipo_documento_cliente varchar(2) NOT NULL,
	k_numero_documento_cliente numeric(10) NOT NULL
)
;

CREATE TABLE "Telefono_Cliente"
(
	k_telefono_contacto numeric(10) NOT NULL,
	k_tipo_documento varchar(2) NOT NULL,
	k_numero_documento numeric(10) NOT NULL
)
;

CREATE TABLE "Telefono_Cliente"
(
	k_telefono_contacto numeric(10) NOT NULL,
	k_tipo_documento varchar(2) NOT NULL,
	k_numero_documento numeric(10) NOT NULL
)
;

CREATE TABLE "Telefono_mensajero"
(
	k_telefono_cel_mensajero numeric(10) NOT NULL,	-- Numero de telefono(s) que puede tener el mensajero.
	k_tipo_documento varchar(2) NOT NULL,
	k_numero_documento numeric(10) NOT NULL
)
;

CREATE TABLE "Trayecto"
(
	k_id_servicio integer NOT NULL,	-- Numero de identificacion propio del servicio.
	k_id_ruta numeric(10) NOT NULL,	-- Numero de identificación propio de la ruta a tomar en el trayecto.
	n_descripcion varchar(500) NOT NULL,	-- Descripción de la actividad que deberá realizar el mensajero en cada dirección. 
	o_calle varchar(20) NOT NULL,	-- Calle de la dirección donde se calculará el trayecto.
	v_numero numeric(3) NOT NULL,	-- Numero de la dirección donde se calculará el trayecto.
	o_barrio varchar(30) NOT NULL	-- Barrio de la dirección donde se calculará el trayecto.
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE "Categoria" ADD CONSTRAINT "PK_Categoria"
	PRIMARY KEY (id_categoria)
;

ALTER TABLE "Categoria" ADD CONSTRAINT "CK_id_categoria" CHECK (id_categoria > 0)
;

ALTER TABLE "Ciudad" ADD CONSTRAINT "PK_Ciudad"
	PRIMARY KEY (k_codigo_postal)
;

ALTER TABLE "Ciudad" ADD CONSTRAINT "CK_v_costo_por_trayecto" CHECK (v_costo_por_trayecto > 0)
;

ALTER TABLE "Ciudad" ADD CONSTRAINT "CK_k_codigo_postal" CHECK (k_codigo_postal > 0)
;

ALTER TABLE "Cliente" ADD CONSTRAINT "PK_Cliente"
	PRIMARY KEY (k_tipo_documento,k_numero_documento)
;

ALTER TABLE "Cliente" ADD CONSTRAINT "CK_k_tipo_documento" CHECK (k_tipo_documento in ('C.C','C.E'))
;

ALTER TABLE "Cliente" ADD CONSTRAINT "CK_k_numero_documento" CHECK (k_numero_documento > 0 )
;

ALTER TABLE "Cliente" ADD CONSTRAINT "CK_v_numero" CHECK (v_numero > 0)
;

ALTER TABLE "Cliente" ADD CONSTRAINT "PK_Cliente"
	PRIMARY KEY (k_tipo_documento)
;


ALTER TABLE "Cliente" ADD CONSTRAINT "CK_v_numero" CHECK (v_numero > 0)
;

ALTER TABLE "Correo_Cliente" ADD CONSTRAINT "PK_Correo_Cliente"
	PRIMARY KEY (k_correo_cliente,k_tipo_documento,k_numero_documento)
;

CREATE INDEX "IXFK_Correo_Cliente_Cliente" ON "Correo_Cliente" (k_tipo_documento ASC,k_numero_documento ASC)
;

ALTER TABLE "Correo_Cliente" ADD CONSTRAINT "PK_Correo_Cliente"
	PRIMARY KEY (k_correo_cliente,k_tipo_documento,k_numero_documento)
;

ALTER TABLE "Correo_Cliente" ADD CONSTRAINT "CK_k_tipo_documento" CHECK (k_tipo_documento in ('C.C','C.E'))
;

ALTER TABLE "Correo_Cliente" ADD CONSTRAINT "CK_k_numero_documento" CHECK (k_numero_documento > 0)
;

CREATE INDEX "IXFK_Correo_Cliente_Cliente" ON "Correo_Cliente" (k_tipo_documento ASC,k_numero_documento ASC)
;

ALTER TABLE "Correo_mensajero" ADD CONSTRAINT "PK_Correo_mensajero"
	PRIMARY KEY (k_correo_elect_mensajero,k_tipo_documento,k_numero_documento)
;

ALTER TABLE "Correo_mensajero" ADD CONSTRAINT "CK_k_tipo_documento" CHECK (k_tipo_documento in ('C.C','C.E'))
;

ALTER TABLE "Correo_mensajero" ADD CONSTRAINT "CK_k_numero_documento" CHECK (k_numero_documento > 0)
;

CREATE INDEX "IXFK_Correo_mensajero_Mensajero" ON "Correo_mensajero" (k_tipo_documento ASC,k_numero_documento ASC)
;

ALTER TABLE "Estado" ADD CONSTRAINT "PK_Estado"
	PRIMARY KEY (k_id_servicio,k_estado_servicio)
;

ALTER TABLE "Estado" ADD CONSTRAINT "CK_k_id_servicio" CHECK (k_id_servicio > 0)
;

CREATE INDEX "IXFK_Estado_Servicio" ON "Estado" (k_id_servicio ASC)
;

ALTER TABLE "Jornada" ADD CONSTRAINT "PK_Jornada"
	PRIMARY KEY (k_dia,k_tipo_documento,k_numero_documento)
;

ALTER TABLE "Jornada" ADD CONSTRAINT "CK_k_dia" CHECK (k_dia IN ('Lunes', 'Martes', 'Miercoles', 'Jueves', 'Viernes', 'Sabado', 'Domingo'))
;

ALTER TABLE "Jornada" ADD CONSTRAINT "CK_k_tipo_documento" CHECK (k_tipo_documento in ('C.C','C.E'))
;

ALTER TABLE "Jornada" ADD CONSTRAINT "CK_k_numero_documento" CHECK (k_numero_documento > 0)
;

CREATE INDEX "IXFK_Jornada_Mensajero" ON "Jornada" (k_tipo_documento ASC,k_numero_documento ASC)
;

ALTER TABLE "Mensajero" ADD CONSTRAINT "PK_Mensajero"
	PRIMARY KEY (k_tipo_documento,k_numero_documento)
;

ALTER TABLE "Mensajero" ADD CONSTRAINT "CK_k_tipo_documento" CHECK (k_tipo_documento IN ('CC', 'CE'))
;

ALTER TABLE "Mensajero" ADD CONSTRAINT "CK_v_calificacion_promedio" CHECK (0 <= v_calificacion_promedio  and v_calificacion_promedio <= 5)
;

ALTER TABLE "Mensajero" ADD CONSTRAINT "CK_i_sexo" CHECK (i_sexo IN ('F', 'M'))
;

ALTER TABLE "Mensajero" ADD CONSTRAINT "CK_i_seguridad_social" CHECK (i_seguridad_social IN ('Sí', 'No'))
;

ALTER TABLE "Mensajero" ADD CONSTRAINT "CK_i_estado" CHECK (i_disponible IN ('Sí', 'No'))
;

ALTER TABLE "Mensajero" ADD CONSTRAINT "CK_k_numero_documento" CHECK (0 < k_numero_documento)
;

ALTER TABLE "Mensajero" ADD CONSTRAINT "CK_n_tipo_transporte" CHECK (n_transporte in ('Bicicleta','Moto','Carro'))
;

ALTER TABLE "Producto" ADD CONSTRAINT "PK_Producto"
	PRIMARY KEY (id_producto)
;

ALTER TABLE "Producto" ADD CONSTRAINT "CK_num_id_proveedor" CHECK (num_id_proveedor >= 0)
;

ALTER TABLE "Producto" ADD CONSTRAINT "CK_precio_actual" CHECK (precio_actual > 0)
;

ALTER TABLE "Producto" ADD CONSTRAINT "CK_stock" CHECK (stock >= 0)
;

ALTER TABLE "Producto" ADD CONSTRAINT "CK_cantidad_producto" CHECK (cantidad_producto >= 0)
;

ALTER TABLE "Producto" ADD CONSTRAINT "CK_precio_venta" CHECK (precio_venta >0)
;

ALTER TABLE "Producto" ADD CONSTRAINT "CK_monto_producto " CHECK (monto_producto >= 0)
;

CREATE INDEX "IXFK_Producto_Categoria" ON "Producto" (id_categoria ASC)
;

CREATE INDEX "IXFK_Producto_Proveedor" ON "Producto" (tipo_id_proveedor ASC,num_id_proveedor ASC)
;

CREATE INDEX "IXFK_Producto_Venta" ON "Producto" (id_venta ASC)
;

ALTER TABLE "Servicio" ADD CONSTRAINT "PK_Servicio"
	PRIMARY KEY (k_id_servicio)
;

ALTER TABLE "Servicio" ADD CONSTRAINT "CK_k_id_servicio" CHECK (k_id_servicio > 0)
;

ALTER TABLE "Servicio" ADD CONSTRAINT "CK_q_cantidad_trayectos" CHECK (q_cantidad_trayectos > 0)
;

ALTER TABLE "Servicio" ADD CONSTRAINT "CK_q_comision" CHECK (q_comision > 0)
;

ALTER TABLE "Servicio" ADD CONSTRAINT "CK_v_costo_total" CHECK (v_costo_total > 0)
;

ALTER TABLE "Servicio" ADD CONSTRAINT "CK_v_calificacion" CHECK (v_calificacion > 0)
;

ALTER TABLE "Servicio" ADD CONSTRAINT "CK_k_tipo_documento" CHECK (k_tipo_documento IN ('CC', 'CE'))
;

ALTER TABLE "Servicio" ADD CONSTRAINT "CK_k_numero_documento" CHECK (k_numero_documento > 0)
;

ALTER TABLE "Servicio" ADD CONSTRAINT "CK_i_tipo_ida_vuelta" CHECK (i_tipo_ida_vuelta in ('SI','NO'))
;

CREATE INDEX "IXFK_Servicio_Ciudad" ON "Servicio" (k_codigo_postal ASC)
;

CREATE INDEX "IXFK_Servicio_Cliente" ON "Servicio" (k_tipo_documento_cliente ASC,k_numero_documento_cliente ASC)
;

CREATE INDEX "IXFK_Servicio_Mensajero" ON "Servicio" (k_tipo_documento ASC,k_numero_documento ASC)
;

ALTER TABLE "Telefono_Cliente" ADD CONSTRAINT "PK_Telefono_Cliente"
	PRIMARY KEY (k_telefono_contacto,k_tipo_documento,k_numero_documento)
;

CREATE INDEX "IXFK_Telefono_Cliente_Cliente" ON "Telefono_Cliente" (k_tipo_documento ASC,k_numero_documento ASC)
;

ALTER TABLE "Telefono_Cliente" ADD CONSTRAINT "PK_Telefono_Cliente"
	PRIMARY KEY (k_telefono_contacto,k_tipo_documento,k_numero_documento)
;

ALTER TABLE "Telefono_Cliente" ADD CONSTRAINT "CK_k_telefono_contacto" CHECK (k_telefono_contacto > 0)
;

ALTER TABLE "Telefono_Cliente" ADD CONSTRAINT "CK_k_tipo_documento" CHECK (k_tipo_documento in ('C.C','C.E'))
;

ALTER TABLE "Telefono_Cliente" ADD CONSTRAINT "CK_k_numero_documento" CHECK (k_numero_documento in ('C.C','C.E'))
;

CREATE INDEX "IXFK_Telefono_Cliente_Cliente" ON "Telefono_Cliente" (k_tipo_documento ASC,k_numero_documento ASC)
;

ALTER TABLE "Telefono_mensajero" ADD CONSTRAINT "PK_Telefono"
	PRIMARY KEY (k_telefono_cel_mensajero,k_tipo_documento,k_numero_documento)
;

ALTER TABLE "Telefono_mensajero" ADD CONSTRAINT "CK_k_tipo_documento" CHECK (k_tipo_documento in ('C.C','C.E'))
;

ALTER TABLE "Telefono_mensajero" ADD CONSTRAINT "CK_k_numero_documento" CHECK (k_numero_documento > 0)
;

ALTER TABLE "Telefono_mensajero" ADD CONSTRAINT "CK_k_telefono_cel_mensajero" CHECK (k_telefono_cel_mensajero > 0)
;

CREATE INDEX "IXFK_Telefono_Mensajero" ON "Telefono_mensajero" (k_tipo_documento ASC,k_numero_documento ASC)
;

CREATE INDEX "IXFK_Telefono_mensajero_Mensajero" ON "Telefono_mensajero" (k_tipo_documento ASC,k_numero_documento ASC)
;

ALTER TABLE "Trayecto" ADD CONSTRAINT "PK_Trayectos"
	PRIMARY KEY (k_id_servicio,k_id_ruta)
;

ALTER TABLE "Trayecto" ADD CONSTRAINT "CK_k_id_servicio" CHECK (k_id_servicio > 0)
;

ALTER TABLE "Trayecto" ADD CONSTRAINT "CK_k_id_ruta" CHECK (k_id_ruta > 0)
;

ALTER TABLE "Trayecto" ADD CONSTRAINT "CK_o_calle" CHECK (o_calle > 0)
;

CREATE INDEX "IXFK_Trayecto_Servicio" ON "Trayecto" (k_id_servicio ASC)
;

/* Create Foreign Key Constraints */

ALTER TABLE "Correo_Cliente" ADD CONSTRAINT "FK_Correo_Cliente_Cliente"
	FOREIGN KEY (k_tipo_documento,k_numero_documento) REFERENCES "Cliente" (k_tipo_documento,k_numero_documento) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Estado" ADD CONSTRAINT "FK_Estado_Servicio"
	FOREIGN KEY (k_id_servicio) REFERENCES "Servicio" (k_id_servicio) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Jornada" ADD CONSTRAINT "FK_Jornada_Mensajero"
	FOREIGN KEY (k_tipo_documento,k_numero_documento) REFERENCES "Mensajero" (k_tipo_documento,k_numero_documento) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Producto" ADD CONSTRAINT "FK_Producto_Categoria"
	FOREIGN KEY (id_categoria) REFERENCES "Categoria" (id_categoria) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Servicio" ADD CONSTRAINT "FK_Servicio_Ciudad"
	FOREIGN KEY (k_codigo_postal) REFERENCES "Ciudad" (k_codigo_postal) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Servicio" ADD CONSTRAINT "FK_Servicio_Cliente"
	FOREIGN KEY (k_tipo_documento_cliente,k_numero_documento_cliente) REFERENCES "Cliente" (k_tipo_documento,k_numero_documento) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Servicio" ADD CONSTRAINT "FK_Servicio_Mensajero"
	FOREIGN KEY (k_tipo_documento,k_numero_documento) REFERENCES "Mensajero" (k_tipo_documento,k_numero_documento) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Telefono_mensajero" ADD CONSTRAINT "FK_Telefono_mensajero_Mensajero"
	FOREIGN KEY (k_tipo_documento,k_numero_documento) REFERENCES "Mensajero" (k_tipo_documento,k_numero_documento) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Trayecto" ADD CONSTRAINT "FK_Trayecto_Servicio"
	FOREIGN KEY (k_id_servicio) REFERENCES "Servicio" (k_id_servicio) ON DELETE No Action ON UPDATE No Action
;

/* Create Table Comments, Sequences for Autonumber Columns */

COMMENT ON TABLE "Categoria"
	IS 'Hace referencia a la categoria a la que pertenece cada producto'
;

COMMENT ON COLUMN "Categoria".id_categoria
	IS 'Este atributo ayuda a diferenciar una categoria de otra , la cual servira para clasificar cada producto.'
;

COMMENT ON COLUMN "Categoria".nombre
	IS 'Es el nombre que se le da a la categoria, ej: Shampoo, smartphone, etc.'
;

COMMENT ON COLUMN "Categoria".descripcion
	IS 'Hace referencia a la descripción de cada categoria.'
;

COMMENT ON COLUMN "Cliente".n_primer_nombre
	IS 'Primer del nombre del usuario quien hace uso del servicio. '
;

COMMENT ON COLUMN "Cliente".n_segundo_nombre
	IS 'Segundo nombre del usuario quien hace uso del servicio. '
;

COMMENT ON COLUMN "Cliente".n_primer_apellido
	IS 'Primer del apellido del usuario quien hace uso del servicio.'
;

COMMENT ON COLUMN "Cliente".n_segundo_apellido
	IS 'Segundo apellido del usuario quien hace uso del servicio.'
;

COMMENT ON COLUMN "Cliente".k_tipo_documento
	IS 'Tipo de documento de indentificación del cliente(CC , TI, CE, pasaporte).'
;

COMMENT ON COLUMN "Cliente".n_primer_nombre
	IS 'Primer del nombre del usuario quien hace uso del servicio. '
;

COMMENT ON COLUMN "Cliente".n_segundo_nombre
	IS 'Segundo del nombre del usuario quien hace uso del servicio.'
;

COMMENT ON COLUMN "Cliente".n_primer_apellido
	IS 'Primer del apellido del usuario quien hace uso del servicio.'
;

COMMENT ON COLUMN "Cliente".n_segundo_apellido
	IS 'Segundodel apellido del usuario quien hace uso del servicio.'
;

COMMENT ON COLUMN "Correo_mensajero".k_correo_elect_mensajero
	IS 'Dirección(es) de correo electronico que puede llegar a tener el mensajero.'
;

COMMENT ON COLUMN "Estado".k_estado_servicio
	IS 'Hace referencia a los 3 posibles estados en que se pueda encontrar el servicio (iniciado, cancelado, terminado). '
;

COMMENT ON COLUMN "Jornada".k_dia
	IS 'Día de la semana en que se dearrolla la jornada del mensajero.'
;

COMMENT ON COLUMN "Jornada".k_tipo_documento
	IS 'Tipo de documento de indentificación del mensajero (CC , TI, CE, pasaporte).'
;

COMMENT ON COLUMN "Jornada".k_numero_documento
	IS 'Numero de identificación del documento del mensajero.'
;

COMMENT ON COLUMN "Jornada".o_hora_inicial
	IS 'Hora en que empieza la jornada del mensajero.'
;

COMMENT ON COLUMN "Jornada".o_hora_final
	IS 'Hora en la que finaliza la jornada del mensajero. '
;

COMMENT ON COLUMN "Mensajero".k_tipo_documento
	IS 'Tipo de documento de indentificación del mensajero (CC , TI, CE, pasaporte).'
;

COMMENT ON COLUMN "Mensajero".k_numero_documento
	IS 'Número de identificación del documento del mensajero.'
;

COMMENT ON COLUMN "Mensajero".v_calificacion_promedio
	IS 'Sumatoria de la puntuación de cada calificación entre el numero de calificaciones hechas por los clientes. '
;

COMMENT ON COLUMN "Mensajero".i_sexo
	IS 'Segundo nombre del mensajero.'
;

COMMENT ON COLUMN "Mensajero".n_nacionalidad
	IS 'Nación, territorio en el que nació el mensajero.'
;

COMMENT ON COLUMN "Mensajero".i_seguridad_social
	IS 'Protección que se le proporciona al mensajero para asegurar el acceso a la asistencia médica y garantizar la seguridad del ingreso.'
;

COMMENT ON COLUMN "Mensajero".n_tipo_medio_transporte
	IS 'Tipo de transporte a serivico del mensajero, el cual puede ser en moto o bicicleta.'
;

COMMENT ON COLUMN "Mensajero".n_tipo_transporte
	IS 'Tipo de paquete transportado (un documento, un paquete pequeño, mediano o grande).'
;

COMMENT ON COLUMN "Mensajero".i_estado
	IS 'Disponibilidad'
;

COMMENT ON TABLE "Producto"
	IS 'Nos referimos a la tabla que almacena la información de cualquier producto dado por el proveedor.'
;

COMMENT ON COLUMN "Producto".id_producto
	IS 'Este atrivuto identifica de forma unica cada producto.'
;

COMMENT ON COLUMN "Producto".nombre
	IS 'Este nombre representa el nombre del producto.'
;

COMMENT ON COLUMN "Producto".precio_actual
	IS 'Hace referencia al precio que actualmente se maneja para el producto por parte del proveedor.'
;

COMMENT ON COLUMN "Producto".stock
	IS 'Hace referencia a la cantidad disponible de este producto, el valor de este puede variar.'
;

COMMENT ON COLUMN "Producto".cantidad_producto
	IS 'Hace referencia a la cantidad que se compra de un producto'
;

COMMENT ON COLUMN "Producto".precio_venta
	IS 'Hace referencia al precio que se le da al producto al momento de venderlo'
;

COMMENT ON COLUMN "Producto".monto_producto
	IS 'Hace referencia al costo total de una misma cantidad de productos'
;

COMMENT ON COLUMN "Producto".id_venta
	IS 'Hace referencia a la identificación de la venta.'
;

COMMENT ON COLUMN "Servicio".n_tipo_transporte
	IS 'Tipo de paquete transportado (un documento, un paquete pequeño, mediano o grande).'
;

COMMENT ON COLUMN "Servicio".i_tipo_ida_vuelta
	IS 'Indica si el servicio es de ida y vuelta, para los casos en que el mensajero tiene que volver al punto de partida. '
;

COMMENT ON COLUMN "Telefono_mensajero".k_telefono_cel_mensajero
	IS 'Numero de telefono(s) que puede tener el mensajero.'
;

COMMENT ON COLUMN "Trayecto".k_id_servicio
	IS 'Numero de identificacion propio del servicio.'
;

COMMENT ON COLUMN "Trayecto".k_id_ruta
	IS 'Numero de identificación propio de la ruta a tomar en el trayecto.'
;

COMMENT ON COLUMN "Trayecto".n_descripcion
	IS 'Descripción de la actividad que deberá realizar el mensajero en cada dirección. '
;

COMMENT ON COLUMN "Trayecto".o_calle
	IS 'Calle de la dirección donde se calculará el trayecto.'
;

COMMENT ON COLUMN "Trayecto".v_numero
	IS 'Numero de la dirección donde se calculará el trayecto.'
;

COMMENT ON COLUMN "Trayecto".o_barrio
	IS 'Barrio de la dirección donde se calculará el trayecto.'
;
