/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 15.1 		*/
/*  Created On : 23-ago.-2020 12:54:06 p. m. 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Tables */

DROP TABLE IF EXISTS Ciudad CASCADE
;

DROP TABLE IF EXISTS Cliente CASCADE
;

DROP TABLE IF EXISTS Correo_Cliente CASCADE
;

DROP TABLE IF EXISTS Correo_mensajero CASCADE
;

DROP TABLE IF EXISTS Estado CASCADE
;

DROP TABLE IF EXISTS Jornada CASCADE
;

DROP TABLE IF EXISTS Mensajero CASCADE
;

DROP TABLE IF EXISTS Servicio CASCADE
;

DROP TABLE IF EXISTS Telefono_Cliente CASCADE
;

DROP TABLE IF EXISTS Telefono_mensajero CASCADE
;

DROP TABLE IF EXISTS Trayecto CASCADE
;

/* Create Tables */

CREATE TABLE Ciudad
(
	k_codigo_postal numeric(5) NOT NULL,	-- Código postal de la ciudad donde se presta el servicio de mensajería.
	n_nombre varchar(30) NOT NULL,	-- Nombre de la ciudad donde se presta el servicio de mensajería.
	v_costo_por_trayecto numeric(10,2) NOT NULL	-- Costo por un trayecto de la ciudad donde se presta el servicio de mensajeria.
)
;

CREATE TABLE Cliente
(
	k_tipo_documento varchar(3) NOT NULL,	-- Tipo de documento de indentificación del cliente (C.C , T.I, C.E, pasaporte).
	k_numero_documento numeric(10) NOT NULL,	-- Numero de documento de indentificación del cliente.
	n_primer_nombre varchar(20) NOT NULL,	-- Primer del nombre del usuario quien hace uso del servicio. 
	n_segundo_nombre varchar(20) NULL,	-- Segundo nombre del usuario quien hace uso del servicio. 
	n_primer_apellido varchar(20) NOT NULL,	-- Primer del apellido del usuario quien hace uso del servicio.
	n_segundo_apellido varchar(20) NULL,	-- Segundo apellido del usuario quien hace uso del servicio.
	o_calle varchar(20) NOT NULL,	-- Calle donde reside el cliente.
	v_numero numeric(3) NOT NULL,	-- Numero de la calle y carrera donde vive el cliente.
	o_barrio varchar(30) NOT NULL,	-- Barrio donde vive el cliente.
	o_ciudad varchar(30) NOT NULL	-- Ciudad donde vive el cliente
)
;

CREATE TABLE Correo_Cliente
(
	k_correo_cliente varchar(30) NOT NULL,	-- Dirección de correo electronico que puede llegar a tener el cliente.
	k_tipo_documento varchar(3) NOT NULL,	-- Tipo de documento de indentificación del cliente (C.C , T.I, C.E, pasaporte).
	k_numero_documento numeric(10) NOT NULL	-- Numero de documento de indentificación del cliente.
)
;

CREATE TABLE Correo_mensajero
(
	k_correo_elect_mensajero varchar(30) NOT NULL,	-- Dirección de correo electronico que puede llegar a tener el mensajero.
	k_tipo_documento varchar(3) NOT NULL,	-- Tipo de documento de indentificación del mensajero (C.C , T.I, C.E, pasaporte).
	k_numero_documento numeric(10) NOT NULL	-- Numero de documento de indentificación del mensajero.
)
;

CREATE TABLE Estado
(
	k_id_servicio integer NOT NULL,	-- Identificador del servicio.
	k_estado_servicio varchar(9) NOT NULL,	-- Hace referencia a los 3 posibles estados en que se pueda encontrar el servicio (iniciado, cancelado, terminado). 
	f_cambio_estado date NOT NULL,	-- Fecha de cambio del estado.
	n_descripcion varchar(200) NOT NULL	-- Descripción del cambio de estado, ya sea porque se realizo el servicio exitosamente, la razón por la cual se cancelo o los comentarios que decee hacer al iniciarlo.
)
;

CREATE TABLE Jornada
(
	k_dia varchar(9) NOT NULL,	-- Día de la semana en que se desarrolla la jornada del mensajero.
	k_tipo_documento varchar(3) NOT NULL,	-- Tipo de documento de indentificación del mensajero (C.C , T.I, C.E, pasaporte).
	k_numero_documento numeric(10) NOT NULL,	-- Numero de identificación del documento del mensajero.
	o_hora_inicial time(5) without time zone NOT NULL,	-- Hora en que empieza la jornada del mensajero.
	o_hora_final time(5) without time zone NOT NULL	-- Hora en la que finaliza la jornada del mensajero. 
)
;

CREATE TABLE Mensajero
(
	k_tipo_documento varchar(3) NOT NULL,	-- Tipo de documento de indentificación del mensajero (C.C , T.I, C.E, pasaporte).
	k_numero_documento numeric(10) NOT NULL,	-- Número de identificación del documento del mensajero.
	n_primer_nombre varchar(20) NOT NULL,	-- Primer nombre del mensajero.
	n_segundo_nombre varchar(20) NULL,	-- Segundo nombre del mensajero.
	n_primer_apellido varchar(20) NOT NULL,	-- Primer apellido del mensajero.
	n_segundo_apellido varchar(20) NULL,	-- Segundo apellido del mensajero.
	v_calificacion_promedio numeric(2,1) NULL,	-- Promedio de la puntuación de cada calificación entre el numero de calificaciones hechas por los clientes. 
	i_sexo char(1) NOT NULL,	-- Sexo del mensajero, puede ser M masculino o  F femenino.
	n_nacionalidad varchar(20) NOT NULL,	-- Nación, territorio en el que nació el mensajero.
	f_nacimiento date NOT NULL,	-- Fecha de nacimineto en la que nació el mensajero.
	i_seguridad_social char(2) NOT NULL,	-- Protección que se le proporciona al mensajero para asegurar el acceso a la asistencia médica y garantizar la seguridad del ingreso.
	n_tipo_medio_transporte varchar(9) NOT NULL,	-- Tipo de transporte a serivico del mensajero, el cual puede ser en moto, bicicleta o carro.
	v_pago_acumulado numeric(10,2) NULL,	-- Es la suma de las comisiones que tendran los mensajeros por cada uno de los servicios prestados.
	n_tipo_transporte varchar(50) NOT NULL,	-- Tipo de paquete transportado (un documento, un paquete pequeño, mediano o grande).
	i_estado char(2) NOT NULL	-- Es la disponibilidad que tiene el mensajero, este  se puede llenar unicamente con SI  o NO 
)
;

CREATE TABLE Servicio
(
	k_id_servicio integer NOT NULL,	-- Numero de identificación de cada servicio.
	q_cantidad_trayectos integer NOT NULL,	-- Es la cantidad de trayectos que tendra el servicio.
	n_tipo_transporte varchar(14) NOT NULL,	-- Tipo de paquete transportado (un documento, un paquete pequeño, mediano o grande).
	i_tipo_ida_vuelta char(2) NOT NULL,	-- Indica si el servicio es de ida y vuelta, para los casos en que el mensajero tiene que volver al punto de partida. 
	f_inicio date NOT NULL,	-- Fecha en la cual se pidio el servicio.
	o_hora_inicio time(5) without time zone NOT NULL,	-- Hora en la que el servicio inicio.
	q_comision integer NOT NULL,	-- La comisión es el pago que recibirá  el mensajero por ese servicio.
	v_costo_total numeric(10,2) NOT NULL,	-- Sera el costo total del servicio, se calculara con el costo por trayecto multiplicado por la cantidad de trayectos.
	v_calificacion integer NULL,	-- Calificación dada por el usuario al mensajero por este servicio prestado.
	k_codigo_postal numeric(5) NOT NULL,	-- Codigo postal de la ciudad donde se hace este servicio.
	k_tipo_documento varchar(3) NOT NULL,	-- Tipo de documento de indentificación del mensajero (C.C , T.I, C.E, pasaporte).
	k_numero_documento numeric(10) NOT NULL,	-- Numero de documento de indentificación del mensajero. 
	k_tipo_documento_cliente varchar(3) NOT NULL,	-- Tipo de documento de indentificación del cliente (C.C , T.I, C.E, pasaporte).
	k_numero_documento_cliente numeric(10) NOT NULL	-- Numero de documento de indentificación del cliente.
)
;

CREATE TABLE Telefono_Cliente
(
	k_telefono_contacto numeric(10) NOT NULL,	-- Numero de telefono que puede tener el cliente.
	k_tipo_documento varchar(3) NOT NULL,	-- Tipo de documento de indentificación del cliente (C.C , T.I, C.E, pasaporte).
	k_numero_documento numeric(10) NOT NULL	-- Numero de documento de indentificación del cliente.
)
;

CREATE TABLE Telefono_mensajero
(
	k_telefono_cel_mensajero numeric(10) NOT NULL,	-- Numero de telefono que puede tener el mensajero.
	k_tipo_documento varchar(3) NOT NULL,	-- Tipo de documento de indentificación del mensajero (C.C , T.I, C.E, pasaporte).
	k_numero_documento numeric(10) NOT NULL	-- Numero de documento de indentificación del mensajero.
)
;

CREATE TABLE Trayecto
(
	k_id_servicio integer NOT NULL,	-- Numero de identificacion propio del servicio.
	k_id_ruta numeric(10) NOT NULL,	-- Numero de identificación propio de la ruta a tomar en el trayecto.
	n_descripcion varchar(500) NOT NULL,	-- Descripción de la actividad que deberá realizar el mensajero en cada dirección. 
	o_calle varchar(20) NOT NULL,	-- Calle de la dirección donde se hará el trayecto.
	v_numero numeric(3) NOT NULL,	-- Numero de la dirección donde se hará el trayecto.
	o_barrio varchar(30) NOT NULL	-- Barrio de la dirección donde se hará el trayecto.
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE Ciudad ADD CONSTRAINT PK_Ciudad
	PRIMARY KEY (k_codigo_postal)
;

ALTER TABLE Ciudad ADD CONSTRAINT CK_v_costo_por_trayecto CHECK (v_costo_por_trayecto > 0)
;

ALTER TABLE Ciudad ADD CONSTRAINT CK_k_codigo_postal CHECK (k_codigo_postal > 0)
;

ALTER TABLE Cliente ADD CONSTRAINT PK_Cliente
	PRIMARY KEY (k_tipo_documento,k_numero_documento)
;

ALTER TABLE Cliente ADD CONSTRAINT CK_k_tipo_documento CHECK (k_tipo_documento in ('C.C','C.E','T.I'))
;

ALTER TABLE Cliente ADD CONSTRAINT CK_k_numero_documento CHECK (k_numero_documento > 0 )
;

ALTER TABLE Cliente ADD CONSTRAINT CK_v_numero CHECK (v_numero > 0)
;

ALTER TABLE Correo_Cliente ADD CONSTRAINT PK_Correo_Cliente
	PRIMARY KEY (k_correo_cliente,k_tipo_documento,k_numero_documento)
;

ALTER TABLE Correo_Cliente ADD CONSTRAINT CK_k_tipo_documento CHECK (k_tipo_documento in ('C.C','C.E','T.I'))
;

ALTER TABLE Correo_Cliente ADD CONSTRAINT CK_k_numero_documento CHECK (k_numero_documento > 0)
;

CREATE INDEX IXFK_Correo_Cliente_Cliente ON Correo_Cliente (k_tipo_documento ASC,k_numero_documento ASC)
;

ALTER TABLE Correo_mensajero ADD CONSTRAINT PK_Correo_mensajero
	PRIMARY KEY (k_correo_elect_mensajero,k_tipo_documento,k_numero_documento)
;

ALTER TABLE Correo_mensajero ADD CONSTRAINT CK_k_tipo_documento CHECK (k_tipo_documento in ('C.C','C.E','T.I'))
;

ALTER TABLE Correo_mensajero ADD CONSTRAINT CK_k_numero_documento CHECK (k_numero_documento > 0)
;

CREATE INDEX IXFK_Correo_mensajero_Mensajero ON Correo_mensajero (k_tipo_documento ASC,k_numero_documento ASC)
;

ALTER TABLE Estado ADD CONSTRAINT PK_Estado
	PRIMARY KEY (k_id_servicio,k_estado_servicio)
;

ALTER TABLE Estado ADD CONSTRAINT CK_k_id_servicio CHECK (k_id_servicio > 0)
;

ALTER TABLE Estado ADD CONSTRAINT CK_k_estado_servicio CHECK (k_estado_servicio in ('iniciado', 'cancelado', 'terminado'))
;

CREATE INDEX IXFK_Estado_Servicio ON Estado (k_id_servicio ASC)
;

ALTER TABLE Jornada ADD CONSTRAINT PK_Jornada
	PRIMARY KEY (k_dia,k_tipo_documento,k_numero_documento)
;

ALTER TABLE Jornada ADD CONSTRAINT CK_k_dia CHECK (k_dia IN ('Lunes', 'Martes', 'Miercoles', 'Jueves', 'Viernes', 'Sabado', 'Domingo'))
;

ALTER TABLE Jornada ADD CONSTRAINT CK_k_tipo_documento CHECK (k_tipo_documento in ('C.C','C.E','T.I'))
;

ALTER TABLE Jornada ADD CONSTRAINT CK_k_numero_documento CHECK (k_numero_documento > 0)
;

CREATE INDEX IXFK_Jornada_Mensajero ON Jornada (k_tipo_documento ASC,k_numero_documento ASC)
;

ALTER TABLE Mensajero ADD CONSTRAINT PK_Mensajero
	PRIMARY KEY (k_tipo_documento,k_numero_documento)
;

ALTER TABLE Mensajero ADD CONSTRAINT CK_k_tipo_documento CHECK (k_tipo_documento IN ('C.C', 'C.E','T.I'))
;

ALTER TABLE Mensajero ADD CONSTRAINT CK_v_calificacion_promedio CHECK (0 <= v_calificacion_promedio  and v_calificacion_promedio <= 5)
;

ALTER TABLE Mensajero ADD CONSTRAINT CK_i_sexo CHECK (i_sexo IN ('F', 'M'))
;

ALTER TABLE Mensajero ADD CONSTRAINT CK_i_seguridad_social CHECK (i_seguridad_social IN ('SI', 'NO'))
;

ALTER TABLE Mensajero ADD CONSTRAINT CK_i_estado CHECK (i_estado IN ('SI', 'NO'))
;

ALTER TABLE Mensajero ADD CONSTRAINT CK_k_numero_documento CHECK (0 < k_numero_documento)
;

ALTER TABLE Mensajero ADD CONSTRAINT CK_n_tipo_medio_transporte CHECK (n_tipo_medio_transporte in ('Bicicleta','Moto','Carro'))
;

ALTER TABLE Servicio ADD CONSTRAINT PK_Servicio
	PRIMARY KEY (k_id_servicio)
;

ALTER TABLE Servicio ADD CONSTRAINT CK_k_id_servicio CHECK (k_id_servicio > 0)
;

ALTER TABLE Servicio ADD CONSTRAINT CK_q_cantidad_trayectos CHECK (q_cantidad_trayectos > 0)
;

ALTER TABLE Servicio ADD CONSTRAINT CK_q_comision CHECK (q_comision > 0)
;

ALTER TABLE Servicio ADD CONSTRAINT CK_v_costo_total CHECK (v_costo_total > 0)
;

ALTER TABLE Servicio ADD CONSTRAINT CK_v_calificacion CHECK (v_calificacion >= 0 AND v_calificacion <=5)
;

ALTER TABLE Servicio ADD CONSTRAINT CK_k_tipo_documento CHECK (k_tipo_documento IN ('C.C', 'C.E','T.I'))
;

ALTER TABLE Servicio ADD CONSTRAINT CK_k_numero_documento CHECK (k_numero_documento > 0)
;

ALTER TABLE Servicio ADD CONSTRAINT CK_i_tipo_ida_vuelta CHECK (i_tipo_ida_vuelta in ('SI','NO'))
;

CREATE INDEX IXFK_Servicio_Ciudad ON Servicio (k_codigo_postal ASC)
;

CREATE INDEX IXFK_Servicio_Cliente ON Servicio (k_tipo_documento_cliente ASC,k_numero_documento_cliente ASC)
;

CREATE INDEX IXFK_Servicio_Mensajero ON Servicio (k_tipo_documento ASC,k_numero_documento ASC)
;

ALTER TABLE Telefono_Cliente ADD CONSTRAINT PK_Telefono_Cliente
	PRIMARY KEY (k_telefono_contacto,k_tipo_documento,k_numero_documento)
;

ALTER TABLE Telefono_Cliente ADD CONSTRAINT CK_k_telefono_contacto CHECK (k_telefono_contacto > 0)
;

ALTER TABLE Telefono_Cliente ADD CONSTRAINT CK_k_tipo_documento CHECK (k_tipo_documento in ('C.C','C.E','T.I'))
;

ALTER TABLE Telefono_Cliente ADD CONSTRAINT CK_k_numero_documento CHECK (k_numero_documento > 0)
;

CREATE INDEX IXFK_Telefono_Cliente_Cliente ON Telefono_Cliente (k_tipo_documento ASC,k_numero_documento ASC)
;

ALTER TABLE Telefono_mensajero ADD CONSTRAINT PK_Telefono
	PRIMARY KEY (k_telefono_cel_mensajero,k_tipo_documento,k_numero_documento)
;

ALTER TABLE Telefono_mensajero ADD CONSTRAINT CK_k_tipo_documento CHECK (k_tipo_documento in ('C.C','C.E','T.I'))
;

ALTER TABLE Telefono_mensajero ADD CONSTRAINT CK_k_numero_documento CHECK (k_numero_documento > 0)
;

ALTER TABLE Telefono_mensajero ADD CONSTRAINT CK_k_telefono_cel_mensajero CHECK (k_telefono_cel_mensajero > 0)
;

CREATE INDEX IXFK_Telefono_Mensajero ON Telefono_mensajero (k_tipo_documento ASC,k_numero_documento ASC)
;

CREATE INDEX IXFK_Telefono_mensajero_Mensajero ON Telefono_mensajero (k_tipo_documento ASC,k_numero_documento ASC)
;

ALTER TABLE Trayecto ADD CONSTRAINT PK_Trayectos
	PRIMARY KEY (k_id_servicio,k_id_ruta)
;

ALTER TABLE Trayecto ADD CONSTRAINT CK_k_id_servicio CHECK (k_id_servicio > 0)
;

ALTER TABLE Trayecto ADD CONSTRAINT CK_k_id_ruta CHECK (k_id_ruta > 0)
;

CREATE INDEX IXFK_Trayecto_Servicio ON Trayecto (k_id_servicio ASC)
;

/* Create Foreign Key Constraints */

ALTER TABLE Correo_Cliente ADD CONSTRAINT FK_Correo_Cliente_Cliente
	FOREIGN KEY (k_tipo_documento,k_numero_documento) REFERENCES Cliente (k_tipo_documento,k_numero_documento) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE Estado ADD CONSTRAINT FK_Estado_Servicio
	FOREIGN KEY (k_id_servicio) REFERENCES Servicio (k_id_servicio) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE Jornada ADD CONSTRAINT FK_Jornada_Mensajero
	FOREIGN KEY (k_tipo_documento,k_numero_documento) REFERENCES Mensajero (k_tipo_documento,k_numero_documento) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE Servicio ADD CONSTRAINT FK_Servicio_Ciudad
	FOREIGN KEY (k_codigo_postal) REFERENCES Ciudad (k_codigo_postal) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE Servicio ADD CONSTRAINT FK_Servicio_Cliente
	FOREIGN KEY (k_tipo_documento_cliente,k_numero_documento_cliente) REFERENCES Cliente (k_tipo_documento,k_numero_documento) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE Servicio ADD CONSTRAINT FK_Servicio_Mensajero
	FOREIGN KEY (k_tipo_documento,k_numero_documento) REFERENCES Mensajero (k_tipo_documento,k_numero_documento) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE Telefono_mensajero ADD CONSTRAINT FK_Telefono_mensajero_Mensajero
	FOREIGN KEY (k_tipo_documento,k_numero_documento) REFERENCES Mensajero (k_tipo_documento,k_numero_documento) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE Trayecto ADD CONSTRAINT FK_Trayecto_Servicio
	FOREIGN KEY (k_id_servicio) REFERENCES Servicio (k_id_servicio) ON DELETE No Action ON UPDATE No Action
;

/* Create Table Comments, Sequences for Autonumber Columns */

COMMENT ON TABLE Ciudad
	IS 'Son las ciudades donde se presta el servicio, especificando el nombre y el valor que tiene un trayecto'
;

COMMENT ON COLUMN Ciudad.k_codigo_postal
	IS 'Código postal de la ciudad donde se presta el servicio de mensajería.'
;

COMMENT ON COLUMN Ciudad.n_nombre
	IS 'Nombre de la ciudad donde se presta el servicio de mensajería.'
;

COMMENT ON COLUMN Ciudad.v_costo_por_trayecto
	IS 'Costo por un trayecto de la ciudad donde se presta el servicio de mensajeria.'
;

COMMENT ON TABLE Cliente
	IS 'Es aquel que pidio el servicio'
;

COMMENT ON COLUMN Cliente.k_tipo_documento
	IS 'Tipo de documento de indentificación del cliente (C.C , T.I, C.E, pasaporte).'
;

COMMENT ON COLUMN Cliente.k_numero_documento
	IS 'Numero de documento de indentificación del cliente.'
;

COMMENT ON COLUMN Cliente.n_primer_nombre
	IS 'Primer del nombre del usuario quien hace uso del servicio. '
;

COMMENT ON COLUMN Cliente.n_segundo_nombre
	IS 'Segundo nombre del usuario quien hace uso del servicio. '
;

COMMENT ON COLUMN Cliente.n_primer_apellido
	IS 'Primer del apellido del usuario quien hace uso del servicio.'
;

COMMENT ON COLUMN Cliente.n_segundo_apellido
	IS 'Segundo apellido del usuario quien hace uso del servicio.'
;

COMMENT ON COLUMN Cliente.o_calle
	IS 'Calle donde reside el cliente.'
;

COMMENT ON COLUMN Cliente.v_numero
	IS 'Numero de la calle y carrera donde vive el cliente.'
;

COMMENT ON COLUMN Cliente.o_barrio
	IS 'Barrio donde vive el cliente.'
;

COMMENT ON COLUMN Cliente.o_ciudad
	IS 'Ciudad donde vive el cliente'
;

COMMENT ON TABLE Correo_Cliente
	IS 'Son los posibles correos que tiene el cliente.'
;

COMMENT ON COLUMN Correo_Cliente.k_correo_cliente
	IS 'Dirección de correo electronico que puede llegar a tener el cliente.'
;

COMMENT ON COLUMN Correo_Cliente.k_tipo_documento
	IS 'Tipo de documento de indentificación del cliente (C.C , T.I, C.E, pasaporte).'
;

COMMENT ON COLUMN Correo_Cliente.k_numero_documento
	IS 'Numero de documento de indentificación del cliente.'
;

COMMENT ON TABLE Correo_mensajero
	IS 'Son los posibles correos que puede tener el mensajero'
;

COMMENT ON COLUMN Correo_mensajero.k_correo_elect_mensajero
	IS 'Dirección de correo electronico que puede llegar a tener el mensajero.'
;

COMMENT ON COLUMN Correo_mensajero.k_tipo_documento
	IS 'Tipo de documento de indentificación del mensajero (C.C , T.I, C.E, pasaporte).'
;

COMMENT ON COLUMN Correo_mensajero.k_numero_documento
	IS 'Numero de documento de indentificación del mensajero.'
;

COMMENT ON TABLE Estado
	IS 'Es el estado en el que se encuentra el servicio, se debe especificar la fecha en la que cambio de estado y una descripcion por la cual cambio.'
;

COMMENT ON COLUMN Estado.k_id_servicio
	IS 'Identificador del servicio.'
;

COMMENT ON COLUMN Estado.k_estado_servicio
	IS 'Hace referencia a los 3 posibles estados en que se pueda encontrar el servicio (iniciado, cancelado, terminado). '
;

COMMENT ON COLUMN Estado.f_cambio_estado
	IS 'Fecha de cambio del estado.'
;

COMMENT ON COLUMN Estado.n_descripcion
	IS 'Descripción del cambio de estado, ya sea porque se realizo el servicio exitosamente, la razón por la cual se cancelo o los comentarios que decee hacer al iniciarlo.'
;

COMMENT ON TABLE Jornada
	IS 'La jornada son los dias y las horas en las que el mensajero estara disponible para hacer un servicio'
;

COMMENT ON COLUMN Jornada.k_dia
	IS 'Día de la semana en que se desarrolla la jornada del mensajero.'
;

COMMENT ON COLUMN Jornada.k_tipo_documento
	IS 'Tipo de documento de indentificación del mensajero (C.C , T.I, C.E, pasaporte).'
;

COMMENT ON COLUMN Jornada.k_numero_documento
	IS 'Numero de identificación del documento del mensajero.'
;

COMMENT ON COLUMN Jornada.o_hora_inicial
	IS 'Hora en que empieza la jornada del mensajero.'
;

COMMENT ON COLUMN Jornada.o_hora_final
	IS 'Hora en la que finaliza la jornada del mensajero. '
;

COMMENT ON TABLE Mensajero
	IS 'El mensajero sera el encargado de realizar el servicio'
;

COMMENT ON COLUMN Mensajero.k_tipo_documento
	IS 'Tipo de documento de indentificación del mensajero (C.C , T.I, C.E, pasaporte).'
;

COMMENT ON COLUMN Mensajero.k_numero_documento
	IS 'Número de identificación del documento del mensajero.'
;

COMMENT ON COLUMN Mensajero.n_primer_nombre
	IS 'Primer nombre del mensajero.'
;

COMMENT ON COLUMN Mensajero.n_segundo_nombre
	IS 'Segundo nombre del mensajero.'
;

COMMENT ON COLUMN Mensajero.n_primer_apellido
	IS 'Primer apellido del mensajero.'
;

COMMENT ON COLUMN Mensajero.n_segundo_apellido
	IS 'Segundo apellido del mensajero.'
;

COMMENT ON COLUMN Mensajero.v_calificacion_promedio
	IS 'Promedio de la puntuación de cada calificación entre el numero de calificaciones hechas por los clientes. '
;

COMMENT ON COLUMN Mensajero.i_sexo
	IS 'Sexo del mensajero, puede ser M masculino o  F femenino.'
;

COMMENT ON COLUMN Mensajero.n_nacionalidad
	IS 'Nación, territorio en el que nació el mensajero.'
;

COMMENT ON COLUMN Mensajero.f_nacimiento
	IS 'Fecha de nacimineto en la que nació el mensajero.'
;

COMMENT ON COLUMN Mensajero.i_seguridad_social
	IS 'Protección que se le proporciona al mensajero para asegurar el acceso a la asistencia médica y garantizar la seguridad del ingreso.'
;

COMMENT ON COLUMN Mensajero.n_tipo_medio_transporte
	IS 'Tipo de transporte a serivico del mensajero, el cual puede ser en moto, bicicleta o carro.'
;

COMMENT ON COLUMN Mensajero.v_pago_acumulado
	IS 'Es la suma de las comisiones que tendran los mensajeros por cada uno de los servicios prestados.'
;

COMMENT ON COLUMN Mensajero.n_tipo_transporte
	IS 'Tipo de paquete transportado (un documento, un paquete pequeño, mediano o grande).'
;

COMMENT ON COLUMN Mensajero.i_estado
	IS 'Es la disponibilidad que tiene el mensajero, este  se puede llenar unicamente con SI  o NO '
;

COMMENT ON TABLE Servicio
	IS 'Es el servicio a prestar, se debe especificar la cantidad de trayectos que se van a realizar, si es de ida o vuelta, la fecha y la hora en la que se realizara el servicio.'
;

COMMENT ON COLUMN Servicio.k_id_servicio
	IS 'Numero de identificación de cada servicio.'
;

COMMENT ON COLUMN Servicio.q_cantidad_trayectos
	IS 'Es la cantidad de trayectos que tendra el servicio.'
;

COMMENT ON COLUMN Servicio.n_tipo_transporte
	IS 'Tipo de paquete transportado (un documento, un paquete pequeño, mediano o grande).'
;

COMMENT ON COLUMN Servicio.i_tipo_ida_vuelta
	IS 'Indica si el servicio es de ida y vuelta, para los casos en que el mensajero tiene que volver al punto de partida. '
;

COMMENT ON COLUMN Servicio.f_inicio
	IS 'Fecha en la cual se pidio el servicio.'
;

COMMENT ON COLUMN Servicio.o_hora_inicio
	IS 'Hora en la que el servicio inicio.'
;

COMMENT ON COLUMN Servicio.q_comision
	IS 'La comisión es el pago que recibirá  el mensajero por ese servicio.'
;

COMMENT ON COLUMN Servicio.v_costo_total
	IS 'Sera el costo total del servicio, se calculara con el costo por trayecto multiplicado por la cantidad de trayectos.'
;

COMMENT ON COLUMN Servicio.v_calificacion
	IS 'Calificación dada por el usuario al mensajero por este servicio prestado.'
;

COMMENT ON COLUMN Servicio.k_codigo_postal
	IS 'Codigo postal de la ciudad donde se hace este servicio.'
;

COMMENT ON COLUMN Servicio.k_tipo_documento
	IS 'Tipo de documento de indentificación del mensajero (C.C , T.I, C.E, pasaporte).'
;

COMMENT ON COLUMN Servicio.k_numero_documento
	IS 'Numero de documento de indentificación del mensajero. '
;

COMMENT ON COLUMN Servicio.k_tipo_documento_cliente
	IS 'Tipo de documento de indentificación del cliente (C.C , T.I, C.E, pasaporte).'
;

COMMENT ON COLUMN Servicio.k_numero_documento_cliente
	IS 'Numero de documento de indentificación del cliente.'
;

COMMENT ON TABLE Telefono_Cliente
	IS 'Son los posibles telefonos que tiene el cliente.'
;

COMMENT ON COLUMN Telefono_Cliente.k_telefono_contacto
	IS 'Numero de telefono que puede tener el cliente.'
;

COMMENT ON COLUMN Telefono_Cliente.k_tipo_documento
	IS 'Tipo de documento de indentificación del cliente (C.C , T.I, C.E, pasaporte).'
;

COMMENT ON COLUMN Telefono_Cliente.k_numero_documento
	IS 'Numero de documento de indentificación del cliente.'
;

COMMENT ON TABLE Telefono_mensajero
	IS 'Son los posibles telefonos que puede tener el mensajero'
;

COMMENT ON COLUMN Telefono_mensajero.k_telefono_cel_mensajero
	IS 'Numero de telefono que puede tener el mensajero.'
;

COMMENT ON COLUMN Telefono_mensajero.k_tipo_documento
	IS 'Tipo de documento de indentificación del mensajero (C.C , T.I, C.E, pasaporte).'
;

COMMENT ON COLUMN Telefono_mensajero.k_numero_documento
	IS 'Numero de documento de indentificación del mensajero.'
;

COMMENT ON TABLE Trayecto
	IS 'Es una de las posibles rutas que puede tener el servicio. Debe tener una descripcion explicando que se debe hacer en cada trayecto.'
;

COMMENT ON COLUMN Trayecto.k_id_servicio
	IS 'Numero de identificacion propio del servicio.'
;

COMMENT ON COLUMN Trayecto.k_id_ruta
	IS 'Numero de identificación propio de la ruta a tomar en el trayecto.'
;

COMMENT ON COLUMN Trayecto.n_descripcion
	IS 'Descripción de la actividad que deberá realizar el mensajero en cada dirección. '
;

COMMENT ON COLUMN Trayecto.o_calle
	IS 'Calle de la dirección donde se hará el trayecto.'
;

COMMENT ON COLUMN Trayecto.v_numero
	IS 'Numero de la dirección donde se hará el trayecto.'
;

COMMENT ON COLUMN Trayecto.o_barrio
	IS 'Barrio de la dirección donde se hará el trayecto.'
;
